### ISSUE TITLE
Replace Brain Leak

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#106]

**Comment by millerj-tc** [comment]
![viscious bunnybots](https://user-images.githubusercontent.com/3642851/42295408-abd7a892-7faf-11e8-81ff-4a1d35d0f306.jpg)

**Comment by ACG8** [comment]
This seems very powerful in a handless deck. I'm on the fence as to whether it is too good; maybe let's test this iteration and see.

**Comment by millerj-tc** [comment]
The cost templating is how Magic does it

https://magiccards.info/soi/en/171.html

"Discarding a card is part of the ability's activation cost. You can't activate the ability if you have no cards in hand."
