### ISSUE TITLE
Space saving conventions

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#11]
We are discussing:
- "Diver" vs "the diver" on cards
- Creating a symbol to put in ability parentheses that means "bury this card as a cost to activate this ability"  ("_Lucid_ (1, B): [Effect]" would require you to pay 1 resource and bury the card to activate the effect
- A shorthand for the mechanic "You may immediately dive a mind/another player's mind/your own mind with +X plunge. You may not spend additional resources to plunge during this dive." I like this mechanic, but it is wordy. We might consider creating a special verbage for it. Like "You may immediate dive another player's mind with capped plunge +X" (the word "capped" would mean that you can't add onto the plunge with resources.)

**Comment by ACG8** [comment]
Is there any situation where you would want to allow the player to spend additional resources to plunge during a special dive? Maybe that is the exception and we could simply specify when to allow that, rather than specifying when to prohibit it.

**Comment by millerj-tc** [comment]
But even in how you just wrote that, you  added a modifier to the word dive ("special"). I think people will naturally think of it as a different kind of thing. You modified the word dive instead, but either way we're modifying some part of the phrase. So if you write "special dive" on the card rather than "capped plunge," you're still labeling it differently.

If you don't label it differently, because of how it's currently templated, I think it's awkward if the default is that "special dives" don't allow resource expenditure. Because it **just** says "dive" and part of the dive procedure in the rules is that you're allowed to spend resources to plunge. So then you have to add a special addendum that says "When a card instructs you to dive, you cannot spend resources to plunge unless otherwise specified."

From a design space perspective , if there is a special action called a "special dive/capped plunge," it means we can interact with that. Like let's say set 1 we design a few cards with the "special dive" ability. Turns out they're OP and we want to make some cards that interact with them. The verbage to interact with "special dives" is much cleaner:

"Lucid: Cancel a special dive."
vs
"Lucid: Cancel a dive initiated by a card."

**Comment by millerj-tc** [comment]
On "diver" vs "the diver":

https://netrunnerdb.com/en/card/10056 ("the runner" not "runner")
https://magiccards.info/kld/en/76.html ("the creature" not "creature")
https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=12931 ("the monster zone" not "monster zone")

Maybe my resistance to "diver" is just because it seems like the industry standard seems to be "the [thing]"? Not saying we also have to do it that way, but I've read so many Magic cards that that's probably why it feels so off to me.

**Comment by ACG8** [comment]
On capped plunge: I think you are right, but I don't like the "capped" modifier; it sounds awkward. (I am also not a huge fan of "special dive", even though I suggested it).

I can go with "the diver"; the extra word shouldn't take up too much space. I'll edit my therapist cards to use that.

**Comment by millerj-tc** [comment]
I agree about "capped plunge" and "special dive" not sounding great. 

Alternatives:
(Based on accuracy, since you always hit an exact card position)
Targeted dive
Precise dive

(Based on speed, since the cards always say "immediately")
Swift dive

(Based on trickiness, since often these are tricky effects)
Sharp dive
Cunning dive
Artful dive

We should also cut the word "immediately" and make it implied in the special phrase. Abilities can either read something like "Trap: Cancel the dive. You may swift dive +4 the diver." Or "Lucid: After a player resolves a dive against you, you may swift dive them." How do you feel about "You may swift dive +4 them" vs " You may swift dive them with plunge+4." The first one reads a little funny to me.

**Comment by ACG8** [comment]
I agree that the first one sounds strange; I think "dive them with plunge+4" sounds good, but swift dive still sounds odd.

What if you remove the + modifier? So "You may dive them with plunge 4" or "You may dive them with 4 plunge", where the lack of a + indicates that it is a fixed plunge value.

**Comment by millerj-tc** [comment]
Deep Dive
Void Dive
Fathom Dive
Bound Dive
Deja Dive (translation would be "let dive" -- but it's thematic!)
Hypno Dive
Direct Dive
Nimble Dive
Sudden Dive
Rapid Dive
Fleet Dive
Sonic Dive
Agile Dive
Fleet Dive
Zip Dive
Ephemeral Dive
Quick Dive
Beta Dive
Myth Dive
Paradox Dive
Precog Dive
Somatic Dive
Dream Dive
Psycho Dive
Psychic Dive
Sub Dive
Foresight Dive
Insight Dive
Forecasted Dive
Augury Dive
Calculated Dive
Exalted Dive
Devout Dive
Ethereal Dive
Guarded Dive
