### ISSUE TITLE
Buff Cybernetic Foresight

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#110]
Card filtering not that good

**Comment by millerj-tc** [comment]
![cybernetic foresight](https://user-images.githubusercontent.com/3642851/42283835-543521c6-7f70-11e8-8b9f-75541208f456.jpg)

**Comment by ACG8** [comment]
I'm not sure why it limits itself to 8 cards. That's almost the entire mind if you don't have a hand, and is the whole mind if you do. Why not just say "search your mind for any card, draw it, then shuffle your mind"?
