### ISSUE TITLE
Tweak Ij

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#111]
Make compliant with disruption spot pie

**Comment by millerj-tc** [comment]
![ij ops expert](https://user-images.githubusercontent.com/3642851/42283820-4d298ad4-7f70-11e8-9b95-be56b7a834fa.jpg)

**Comment by ACG8** [comment]
A nice contrast with the rustbot, trading flexibility for the ability to reveal multiple cards.
