### ISSUE TITLE
Nerf Zachariel's Arbitration

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#112]
Make it access another player's outer card (or maybe middle?). Also maybe make symmetrical.

**Comment by millerj-tc** [comment]
In dives

**Comment by ACG8** [comment]
I like the symmetry. If you prepare it in the inner position, you don't even lose one of your cards. Strong disruption early game (when people want will), but might be a little weak later compared to dives with positional-bonus-like rewards.
