### ISSUE TITLE
Replace Silence of Leliel

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#113]
Try to make a channel that disrupts combos.

**Comment by millerj-tc** [comment]
![cyberloxo](https://user-images.githubusercontent.com/3642851/42283813-41e90eba-7f70-11e8-8772-01c91864ec00.jpg)

**Comment by ACG8** [comment]
Looks good, though I don't think it disrupts combos. Sure, if everybody is comboing it is quite strong, but I think it only discourages combos on a meta level - in an actual game, if you already have a combo deck there's a tragedy of the commons type scenario where you won't stop comboing just to prevent somebody else from gaining. So more of a strategic than a tactical counter.
