### ISSUE TITLE
Non-lucids with triggered effects

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#121]
Should the rules allow this? It definitely makes the line between lucids and other cards fuzzy.

![the unstoppable hms ingrid](https://user-images.githubusercontent.com/3642851/42258974-01763a3e-7f24-11e8-944b-61a91ffa5cc0.jpg)

**Comment by millerj-tc** [comment]
Maybe this is better

![the unstoppable hms ingrid lucid](https://user-images.githubusercontent.com/3642851/42261238-274a4cc4-7f2d-11e8-89e2-3c6c6a9fd668.jpg)

**Comment by millerj-tc** [comment]
Or this
![the unstoppable hms ingrid lucid](https://user-images.githubusercontent.com/3642851/42283459-2085c17e-7f6f-11e8-9c01-35ce02ed2ec0.jpg)

**Comment by ACG8** [comment]
This card is very powerful. especially compared to Midnight Scoundrel. I absolutely agree that dives should not have lucid-like effects. I don't like how it always triggers no matter what; could the trigger on access have an additional cost? Alternatively, perhaps the bonus access could be restricted to a single position, trading the risk that the Lucid is taken for the risk that no cards are left in that position?

![the unstoppable hms ingrid](https://user-images.githubusercontent.com/10094820/42295588-90a29724-7fb1-11e8-998f-e4b10a5e6058.jpg)
