### ISSUE TITLE
Tweak Mouse?

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#122]
Random hand access deemed mean

**Comment by millerj-tc** [comment]
![consciousness traversing mouse](https://user-images.githubusercontent.com/3642851/42295324-a5abd7dc-7fae-11e8-9552-8aaaabb9744f.jpg)

**Comment by ACG8** [comment]
The new version looks good. Simple, and preserves the functionality of the old one without being too punitive.
