### ISSUE TITLE
Rework recursive cards

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#126]
- Orville
- Achronate
- Eucler

**Comment by ACG8** [comment]
![euclers infinite vault](https://user-images.githubusercontent.com/10094820/43051064-d62f69cc-8dd8-11e8-99ec-73900a1214b2.jpg)
![orville birdfolk pillager](https://user-images.githubusercontent.com/10094820/43051065-d642ad0c-8dd8-11e8-9783-7c6fefb835e2.jpg)
![achronates wheel](https://user-images.githubusercontent.com/10094820/43051066-d6537b5a-8dd8-11e8-8954-ab109a158f6a.jpg)

**Comment by ACG8** [comment]
![orville birdfolk pillager](https://user-images.githubusercontent.com/10094820/43107380-5afedad8-8ea2-11e8-9b48-0d7d112a8cb6.jpg)
