### ISSUE TITLE
Core Lucid not urgent

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#141]
After the prep phase, gain i1.

**Comment by ACG8** [comment]
![shelter from the dark](https://user-images.githubusercontent.com/10094820/43055985-28f64664-8dff-11e8-843f-a4d83298d2f8.jpg)

**Comment by ACG8** [comment]
![safe_by_belovedmeme-d3iyh2t](https://user-images.githubusercontent.com/10094820/43056013-4634d790-8dff-11e8-8469-260199e5b121.jpg)

**Comment by ACG8** [comment]
![shelter from the dark](https://user-images.githubusercontent.com/10094820/43056019-5075f464-8dff-11e8-8fef-314dfcca5a6d.jpg)
