### ISSUE TITLE
Team-up protection card

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#143]
A card you can use for lots of value if you anticipate that you will be double-teamed:

Lucid: After another player accesses one of your other cards: Bury a prepared card to gain i4.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/43719584-b4710e86-9953-11e8-8f3d-3846e8bf8b90.png)

**Comment by ANRTheBigBoy** [comment]
I don't get how this helps.

**Comment by ANRTheBigBoy** [comment]
Seems VERY situational

**Comment by ACG8** [comment]
It helps by focusing enemies against each other. However, if you are anticipating everybody will go for you, I would probably just use Ozilus-type prep-phase card that buries/returns all your cards and gives some appropriate bonus. Then you actually make a prediction, and it does more damage to your enemies.

What if it is at end of prep phase, and it returns outer card, buries inner card, and reveals middle card, and then lets you pay to access your middle card?

**Comment by ACG8** [comment]
![the winter that walks](https://user-images.githubusercontent.com/10094820/43749027-0cad9f4c-99b8-11e8-8270-fd699a639945.jpg)

**Comment by ANRTheBigBoy** [comment]
This is too weird. You could access a dive and then hit another player's card when they are going first. Too many feelbads.

**Comment by millerj-tc** [comment]
I don't like how many positional references it has, but I think the idea of paying something to steal the first player token is worth looking at.

What if it just let you choose to return any other prepared card to your hand and then interpreted your last prepared card at a cost? It's like the new Rippo except you don't even get randomly prepared cards. Unless you put down a Horse and then prepare something...hmm....

What if said: "Return your prepared cards to your hand. Interpret another player's prepared card. They draw a card and may prepare a card."

**Comment by ACG8** [comment]
![the winter that walks](https://user-images.githubusercontent.com/10094820/43806661-7c217bc0-9a6a-11e8-9b14-bc3c8749f80c.jpg)

**Comment by millerj-tc** [comment]
Since this isn't "disruption" (only affects you) I don't think it needs to follow the disruption pie. You can make the card simpler by removing the spot references.

**Comment by ACG8** [comment]
Spot reference is actually simpler; it takes fewer characters than saying "Return one of your prepared cards to your hand" and reduces the number of choices during dive phase. Also has more interesting implications for card placement (sure, you use it after prep but it also limits your own spot bonuses to will (or card draw if not using the second part)).
