### ISSUE TITLE
Term for putting a card on top of a player's deck

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#16]
Many cards have an effect that does this, and it is strange to have bury but no equivalent term for top-decking cards.

Possibilities:
**Raise**
**Lift**

**Comment by millerj-tc** [comment]
It might help with terminology creep if we make the word for "put a card on top" feel related to the proposed new word for "the card on top"

Front
Remind
Evoke
Invoke
Recall
Kindle
Elicit
Awaken
Recollect
Call
Jog
Refresh
Cue
Foreshadow
Manifest
Load
Store
Appoint
Prime

**Comment by millerj-tc** [comment]
I really like evoke, based on its first Google definition: "bring or recall to the conscious mind."

I like cue for brevity.

Those are my top two.

**Comment by ACG8** [comment]
I vote for cue. Evoke makes me think of using the effect of an artifact (or other object).

**Comment by ACG8** [comment]
Can we also use "cued face up" to check whether a card is face up on top of a player's mind?

**Comment by millerj-tc** [comment]
Yeah I like that
