### ISSUE TITLE
"Before/after you dive" confusion

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#17]
Does "after you dive" trigger after you declare a dive but before you do anything else, or only once the dive is resolved? Does "before you dive" mean before you declare the target, or after you declare the target, but before anything else?

Maybe we should be more specific. Like "after a dive is resolved" means after everything in the dive happens and "after/before a/your dive is declared" lets you react to the initiation of the dive before plunge costs, etc.

**Comment by millerj-tc** [comment]
I had already used terminology like this on Deep Unit Alpha in the Thieves starter.  So far no other card we've designed refers to dives being "resolved."

**Comment by ACG8** [comment]
I agree that we should clarify dive resolution vs declaration. I think people would assume that "after you dive" means after resolution, but it is good to be specific.
