### ISSUE TITLE
The Cardinal

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#174]
![image](https://user-images.githubusercontent.com/3642851/43496067-d9f7e8a2-9500-11e8-8783-80245b62847b.png)

**Comment by ANRTheBigBoy** [comment]
I worry this might cause people to go hard into the think tank when given the opportunity to trigger the 2nd ability, giving away that they have the card. Kinda a liability for newbies. Maybe change the 2nd one to: At the end of the dive phase: gain 1 if this is your only prepared card.

**Comment by ACG8** [comment]
So then it is [i1] almost no matter what (easy to arrange things so it is only card)? Seems quite good. Already is [i1] no matter what unless you are not targeted.

We already saw something like this with Hel's deal. For an inevitable effect like this, maybe nerf rewards to card draw to make it more distinct from the Protective Horror?

Why not swap the abilities as well? So draw 3 when another card is interpreted, or draw 1 when this card is interpreted. Then you avoid the "think tank".

**Comment by ANRTheBigBoy** [comment]
I think there already is a card designed here that is the swapped version.

The 1 point is easy, but not automatic. It's very distinct from protective horror I think.

**Comment by ACG8** [comment]
Interruptible Shelter is good if you are trying to obfuscate the location of your dream. The main weakness of Shelter is that it makes it harder to hide the location of your dream (which is more valuable). The same is true of any lucid that triggers before the end of the dream phase. What makes this one so good is that you get a ton of value if they find it, some value if they don't, and it still serves the purpose of being a decoy. Whereas Shelter just gives you 1 insight and then leaves you with only two places to hide your dream.

**Comment by millerj-tc** [comment]
What if the end of dive phase ability was "prepare a card"? That's kind of
interesting because it would make it a very strong card in the last
position and decreasingly effective as you moved towards first?

**Comment by ACG8** [comment]
I think it is strong no matter which position. That would make it a risk-less decoy that can even replace your channel if it is removed. Maybe do that but reduce the insight when it is accessed to [i2]?

**Comment by millerj-tc** [comment]
Oh yeah, I was thinking that if the when this card is interpreted effect
was prepare a card that is better when you're in last. But, if it's the end
of the dive phase effect then it's good for everyone. Maybe the end of the
dive phase affect should just be Draw a card like you said.
