### ISSUE TITLE
Witch Cycle

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#176]
![image](https://user-images.githubusercontent.com/3642851/43496395-d2dacc54-9502-11e8-874d-9324f81e1e7f.png)
![image](https://user-images.githubusercontent.com/3642851/43496397-d4b42c6e-9502-11e8-8d47-e70663e05721.png)
![image](https://user-images.githubusercontent.com/3642851/43496398-d6f80338-9502-11e8-83c5-2238d4eb2c7e.png)

**Comment by ANRTheBigBoy** [comment]
These are all great.

**Comment by millerj-tc** [comment]
I think we should push the power levels of the paid abilities for this cycle.

Theoretically, making everyone else lose i1 should be as good as you gaining i1, but the problem is that it's conditional based on what their plan is. Maybe they are a control deck that doesn't care about losing i1? Therefore, I think you should get a little bit more payoff when you decide to pay the same price as everybody else so that you can draft the one in the cycle where the paid ability fits in with your proactive strategy and feel paid off.

**Comment by ANRTheBigBoy** [comment]
Idk these all seem like good cards to me and I feel like I would trigger the extra ability almost every time on each one. Frost witch's is the weakest, but is still very good in the deck it belongs in.

**Comment by millerj-tc** [comment]
I want to keep my eye on them, because I think I'm the only one who has drafted and played them so far (over 4 drafts), so maybe in theory you would use them, but if no one is actually playing them then it's probably because they are below curve?

**Comment by ACG8** [comment]
Maybe Frost Witch sacrifice 1 for 2? Too good?

Going by conversion rates:

Forest Witch is 0.25 -> 0.5
Frost Witch is 0.5 -> 0.33
Ivory Witch is 0.33 -> 0.5

So with change, Frost Witch becomes 0.5 -> 0.67

**Comment by ANRTheBigBoy** [comment]
I would pick these pretty highly if I saw the one that fit my deck. Last time we drafted I didn't see any after first pick each pack.

**Comment by ACG8** [comment]
I still think Frost witch is too weak, but have no serious objections to including these.
