### ISSUE TITLE
Gloom Ritual

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#179]
![image](https://user-images.githubusercontent.com/3642851/43496939-97b9b254-9505-11e8-86e9-cfcc9028cc9d.png)

**Comment by ANRTheBigBoy** [comment]
This is a weaker Tormented Understudy. Get rid of the Will cost option and let it prepare 2 cards. Then it replaces itself too. Having 2 cards to prepare after burying 2 takes some work. Can make it bury 3 if you're worried.

**Comment by ACG8** [comment]
I agree with @ANRTheBigBoy

**Comment by ANRTheBigBoy** [comment]
Ya that's kinda a wash though. I just don't think I'd ever run this card as is.

**Comment by millerj-tc** [comment]
I think it could be good in a Knowledge of Shadows type deck where you need
to preserve a very specific win condition.
