### ISSUE TITLE
Same Axis Sweeper Cycle

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#180]
![image](https://user-images.githubusercontent.com/3642851/43496962-ae77b87e-9505-11e8-99f1-3bc540b14a11.png)
![image](https://user-images.githubusercontent.com/3642851/43496965-b094e866-9505-11e8-9bed-7405079d89c9.png)
![image](https://user-images.githubusercontent.com/3642851/43496970-b2e5790a-9505-11e8-8c66-3e4601856f80.png)

**Comment by ANRTheBigBoy** [comment]
Monster band is a really big swing. We'll have to test how restrictive the cost feels. It's probably fine. 
Secrets of the Sea is cool. Nice way to get a leg up in the big-will mirror that wont just get used by aggro.
Brain Drain is sweet.
