### ISSUE TITLE
Floof Sanctuary (possible alt to Dream Factory in Core)

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#182]
![image](https://user-images.githubusercontent.com/3642851/43497892-08c0d88e-950a-11e8-97d0-ba8b005b8c99.png)

Teaches players the bury cost, gives a core set payoff for cards in hand, easier to use than Dream Factory currently is.

**Comment by ANRTheBigBoy** [comment]
I'd rather just make it 2 VP each. Less text and better when you are winging it.

**Comment by millerj-tc** [comment]
Cards that use one of each type are weird: they're always on. It's much easier to use then something that just had a bury-a-dream cost and no other typed-bury-costs. I think maybe you're underestimating how strong that version would be, especially as a lucid.

What do you think @ACG8 ?

**Comment by ACG8** [comment]
I agree with @ANRTheBigBoy that it would be better to have less text. However, this card is extremely good for a Lucid already. Easy to trigger and high payoff (though at cost of cards). I would say keep it as is but reduce payoff for using all three abilities to [i2] and see if there is a way to shorten the last part so it only takes 1 line.

**Comment by ANRTheBigBoy** [comment]
I've thought about it some more and I think this is fine. Do ananda's change and make the last ability 2.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/43561466-c5082b96-95dc-11e8-82a6-c214e63d817c.png)
