### ISSUE TITLE
Replace Escorting the Princess in Core

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#184]

**Comment by millerj-tc** [comment]
I think these are also good choices:
![image](https://user-images.githubusercontent.com/3642851/43676596-e5b28056-97b9-11e8-8249-5b3b4c66e30c.png)

![image](https://user-images.githubusercontent.com/3642851/43676597-e8ff635a-97b9-11e8-9c73-ecf850b18d1f.png)

**Comment by ACG8** [comment]
Yeah, I would go with Journey. Core cards should be simple, and with Dream Factory removed Journey fills that role of simple will-to-points.
