### ISSUE TITLE
Replace Dream Expedition in Core

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#185]

**Comment by millerj-tc** [comment]
What about changing Relentless Hunter to a variation of Intergalactic Journey?
![image](https://user-images.githubusercontent.com/3642851/43672874-0e474552-977d-11e8-8b2c-82b07e4ff512.png)

**Comment by millerj-tc** [comment]
Suggested reworks:
![image](https://user-images.githubusercontent.com/3642851/43676559-5b1ff0ea-97b9-11e8-99e4-5cbdfddf9f86.png)
![image](https://user-images.githubusercontent.com/3642851/43676561-5cf90474-97b9-11e8-81a5-34cfa082d912.png)
![image](https://user-images.githubusercontent.com/3642851/43676562-5e3ec9b8-97b9-11e8-8b21-962e54d98de5.png)
![image](https://user-images.githubusercontent.com/3642851/43676563-5f68aeb2-97b9-11e8-979f-35ed236ab8a3.png)

We could also put Entry to the Place of Power into that slot
![image](https://user-images.githubusercontent.com/3642851/43676573-8aa94dca-97b9-11e8-94d2-03216fd41061.png)

**Comment by ANRTheBigBoy** [comment]
Put in the "may not target same player" version. 

For lich king and sharpshooter, you could change them to:
"...reveal another player's prepared card. Gain X unless that player buries that card"

Still rewards you for sniping channels and makes them less swingy if accessed in the dive phase.

**Comment by ACG8** [comment]
I like the version of Relentless Hunter that targets a top card. Easy way to avoid too much disruption.

**Comment by millerj-tc** [comment]
I agree with @ACG8 about Relentless hunter -- the wording is simpler.

**Comment by ACG8** [comment]
Also, I don't think the ability needs to give an [i2] bonus on top of interpreting a second card. Interpreting a second card is already really good because of the chance of hitting a dream.

**Comment by ACG8** [comment]
I don't like "gain X unless that player buries the card" because their only reason to do so is to spite you. Sure, if it is a good card and somebody is going before them they might do it, but if they know they would otherwise be able to use it the best choice is just to give you X and keep the card; burying it to deny you points doesn't benefit them any more than it benefits the other players and hurts them.

**Comment by millerj-tc** [comment]
**Relentless Hunter**
Cf with Underworld Guide (pay 4 and you know what you're getting) and Intergalactic Journey (worse because it's modal, but you're getting an i4 bonus and accessing their top card). No one hardly ever plays these cards. If that rate for an access is too good I don't think it's been demonstrated yet. Further, what if you hit Fallen Titan with no 6+ cost cards or Beleaguered Delivery with 0 cards in hand? I don't think the chance of hitting a dream is actually that high of an EV. Could we drop it to an i1 bonus?

**Snipers**
Maybe we should just cut this design? The game already should be rewarding you for sniping dreams because you're getting an extra dream and denying another player their dream. I don't think we need to encourage it any more since the base mechanics now do that dynamically. Also I think part of the skill of the game is understanding when to deviate from the common practice of attacking left to disrupting a threat -- this kind of puts that on autopilot since it gives you two single target disruption actions in a single turn.

**Comment by ACG8** [comment]
**Relentless Hunter**
Sure, i1 is fine with me.

**Snipers**
Agreed. Snipers not that interesting.
