### ISSUE TITLE
Lucid Trigger Exchange Rates

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#187]
I think it's about like this:
(Easiest to trigger)
- After you interpret a card
- After the prep phase
- After another one of your cards is interpreted
- After the dive phase
- After this card is interpreted
(Hardest to trigger)

For reference, here is how most of the current lucids fit in

****
**AFTER YOU INTERPRET A CARD**  (there is a slight difference between "after...another player's," and "after...your own")
![image](https://user-images.githubusercontent.com/3642851/43715231-6c60d940-9945-11e8-80f3-2f2678411e20.png)
![image](https://user-images.githubusercontent.com/3642851/43715251-805bd396-9945-11e8-8d4f-aa18a474041f.png)
![image](https://user-images.githubusercontent.com/3642851/43715256-82a24a0e-9945-11e8-83c1-28164c0c3cb0.png)
![image](https://user-images.githubusercontent.com/3642851/43715270-8a53f22a-9945-11e8-9a88-ad41f073e0f1.png)
![image](https://user-images.githubusercontent.com/3642851/43715280-9628ee3e-9945-11e8-8764-4c653374505d.png)
![image](https://user-images.githubusercontent.com/3642851/43716557-297f4d28-994a-11e8-916d-93a59d7a9769.png)

**AFTER THE PREP PHASE**
![image](https://user-images.githubusercontent.com/3642851/43715313-bb0de268-9945-11e8-8cc6-bc4b53f9e534.png)
![image](https://user-images.githubusercontent.com/3642851/43715319-bd626c50-9945-11e8-8e99-43997d7d083f.png)
![image](https://user-images.githubusercontent.com/3642851/43715333-c81970da-9945-11e8-9088-e3c53bc9ed43.png)
![image](https://user-images.githubusercontent.com/3642851/43715342-d393bc72-9945-11e8-916a-ac075e8bf0b2.png)

**AFTER ANOTHER ONE OF YOUR CARDS IS INTERPRETED** (and hybrid cards)
![image](https://user-images.githubusercontent.com/3642851/43715359-e36cf168-9945-11e8-9baf-d159a703fd8c.png)
![image](https://user-images.githubusercontent.com/3642851/43715366-edbea0a8-9945-11e8-9426-dacd32bfe933.png)
![image](https://user-images.githubusercontent.com/3642851/43715369-ef753e52-9945-11e8-8c7d-4d7ebfc24277.png)
![image](https://user-images.githubusercontent.com/3642851/43715371-f0e87bbe-9945-11e8-8486-23bf9804e213.png)
![image](https://user-images.githubusercontent.com/3642851/43715378-f40fe21e-9945-11e8-8cac-b8e9abea3be2.png)
![image](https://user-images.githubusercontent.com/3642851/43715381-f63d2baa-9945-11e8-9d32-28d890c53e81.png)

**AFTER THE DIVE PHASE**
![image](https://user-images.githubusercontent.com/3642851/43715409-0ca7924a-9946-11e8-90b5-4d4e0cbbd061.png)
![image](https://user-images.githubusercontent.com/3642851/43715411-0fc0f232-9946-11e8-817d-7afb92bf7768.png)
![image](https://user-images.githubusercontent.com/3642851/43715414-12090214-9946-11e8-8989-d01b6962d040.png)

**AFTER THIS CARD IS INTERPRETED**
![image](https://user-images.githubusercontent.com/3642851/43715472-35fb0640-9946-11e8-97d3-367ce5bec4d8.png)

**WEIRDOS**
![image](https://user-images.githubusercontent.com/3642851/43715478-3dbd7200-9946-11e8-8a64-1f69941d556d.png)
![image](https://user-images.githubusercontent.com/3642851/43715481-437b6792-9946-11e8-937d-39964df1d30e.png)
![image](https://user-images.githubusercontent.com/3642851/43715513-58091bfa-9946-11e8-952b-53ceff821e00.png)

**Comment by millerj-tc** [comment]
I think maybe we should do two things:
1) Establish a baseline value (how much of a base dream do you get for free from this kind of trigger)
2) Establish a "tax" (if it has a cost associated with it, there should be some kind of bump to balance the fact that you can stack lucids with other card types). We could also decide that some of the harder ones get a "discount"?

For instance, if the regular exchange rate of will:insight is about 1:1, we might decide that the "tax" on "after you interpret another player's card" is one base dream (i3, w2, or d4). That puts Journey Up the Mountain on curve. You "tax" it, then apply the regular exchange rate on top of that w2  (one base dream)+w2/2i = w4:i2

**Comment by ACG8** [comment]
After the prep phase is by far the easiest trigger.

**Comment by ACG8** [comment]
Also, I think After the Dive Phase is more difficult than After This is Triggered, judging by how many cards regularly get accessed right now. You can bait After This is Triggered especially easy when you go first if you bury your other two cards.

**Comment by ACG8** [comment]
**Prep phase** is pretty simple; I think Shelter from the Dark is pretty fair right now (possibly even slightly weak), so it serves as a good baseline. [i1], [w1], [d1] all seem pretty fair (maybe [d2]) for prep phase.

**Comment by ACG8** [comment]
Or in other words, 0.3-0.5

**Comment by ACG8** [comment]
Hmm, maybe we should add a wiki page for card strength guidelines. I'll get on that now.

**Comment by millerj-tc** [comment]
I put After the Prep second because it comes with a universal drawback. If you're going first, an After Interpret card is basically the same. If you're going last, an After Interpret is safer in some ways because it's still a dream decoy until you go and use it. I think it depends on what you are trying to do, but if you are trying to get value out of the dream phase (which players often are), I think After Interpret is stronger, and therefore deserves the highest tax rate.

What do you think  @ANRTheBigBoy ?

**Comment by ACG8** [comment]
I don't think we should take "utility as a dream decoy" into account, just ease of triggering. We're trying to determine how strong to make the effects balanced against how often they go off. An effect that practically always goes off should be accordingly weaker than an effect that could be stopped if somebody gets the card first. If you really want a dream decoy, you can always choose not to trigger the card.

The risk of a post-prep card not going off is substantially lower than the risk of a post-interpret card not going off. The reward should therefore be lower as well.

**Comment by ACG8** [comment]
I think post-interpret cards should be slightly stronger in power than dives, because they go off at about the same time but don't have the spot bonus. So they should be 0.25-0.5 units stronger than a dive card with a similar effect (though you have to take into account the extra access the dive gives you. Hmm.)

**Comment by ACG8** [comment]
And post-dive phase lucids should be similar to dreams because they trigger at nearly the same time. A little weaker, perhaps, since the trigger earlier and don't count toward the dream limit.

**Comment by ACG8** [comment]
Another reason to look only at how likely a lucid is to trigger is that we don't know what other cards are out. If the other cards are traps, you want to narrow the choices, and they might be post prep lucid's or something else that doesn't need dream decoys. So I don't think we should consider other cards the player might have because we don't know the context in which a post prep lucid is being played; we only have the card itself to judge. We shouldn't assume the player will always be hiding a dream, since the rules don't require that.

**Comment by ANRTheBigBoy** [comment]
After Prep: .5 Core Dream Value
After interpret: .65
Trap: .5-.65 (depending on if it triggers on itself or not)

It's ok to be off from these, but they are decent guidelines. More flexible effects can be worth less. 

After the dive phase effects should be unique things like swordswomen/prepare effects. Harder to evaluate.

**Comment by millerj-tc** [comment]
So this is what you get for free or this is the tax? I think we should establish both values.

**Comment by ACG8** [comment]
See https://github.com/ACG8/Lucid/wiki/Card-Strength-Guidelines

Assuming @ANRTheBigBoy is using the same system as I am, these are the target strengths for any effects attached to the trigger.

So e.g. an After Prep trigger should provide a benefit of approximately 0.5 units, while an After Interpret gives a benefit of approximately 0.65.
