### ISSUE TITLE
Switch i15 condition to i20?

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#188]
The second ability should probably turn on at i20 now, right?

![image](https://user-images.githubusercontent.com/3642851/43715959-e7c6f82e-9947-11e8-8495-1fc30b6612b9.png)

**Comment by ANRTheBigBoy** [comment]
I think 15 is fine. Also we should make a reverse card of this. Gain w2 and drain each player with at least 15 for 2.

**Comment by ACG8** [comment]
15 is fine, until evidence to contrary.

**Comment by millerj-tc** [comment]
@ANRTheBigBoy I'm  not sure the card you are suggesting is sufficiently different from Aristocratic Mirror. I mean, there is a difference, I'm just not sure if it's an interesting one.

**Comment by ANRTheBigBoy** [comment]
Ya that's true.
