### ISSUE TITLE
December 26th 2017 Playtest

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#19]
Players: Joseph, Joe Downing, Aaron Cavanough-Broad
Played with the party set, pretty late at night

# Playtester Notes

Randomizing the first player while also changing the play direction was hard while tired. I gave up on changing play direction halfway through the first game and we played in a predetermined order for the second game with no play direction switching.
**Solution: Each card buried during prep gives you +1 initiative. The player with the most initiative gets to go first. The player who went first last round cannot go first again. In case of a tie, the player who is closest (clockwise) to the first player token will go first.**

Playtesters noted that accessing a barrier (on top) felt bad because it gave other players free information, but didn't help the accessing player because they couldn't dive again with that info. At least with traps there was a sense of danger/getting caught but accessing a barrier just feels like _bleh_. This came up multiple times, with both players suggesting that barrier cards be green split cards so that when you accessed them (rather than plunged past them) you could get some sort of advantage.
**I think part of this is that the party barriers were too good, so keeping them on top always made sense and therefore people were accessing them a lot but then declining to bury them because they didn't want to clear the way for the next player. Once the party barriers are appropriately nerfed, we will see if people still feel this way.**

Playtester requested a game action alternative to diving. If you anticipate that all players have cued a trap (and you know you have as well), and don't want to spend resources to dive, it feels like there is nothing you can do. 
**Solution: Allow a player to pass on dives and look (privately) at their own third/fourth card (depending if you are using the draw 2 or draw 3 during prep rule). Then they may shuffle their mind if they wish.**

Playtesters noted that they wished there were more catchup mechanics for when you fell behind.
**Solution: Part of this seems solved by personal deckbuilding choices. In Magic, for instance, sometimes you play a deck that can only really grind it out, whereas other people play decks that are more swingy. It's just personal preference and they are balanced within the meta. However, I do think that since the party set specifically can feel so nickel-and-dime-y, that it would benefit for some kind of "swing for the fences" card that allows you to surpass someone who has ground out a lead if you are willing to take a risk.**

Playtesters said that plunging other minds could feel bad because you don't always access something good and give away a lot of free info to other players. In one game, I plunged another player for 4 and the player after me did the same thing since they knew there were no barriers on top, so they were able to trigger the ID passive "for free" -- although I think they did wind up hitting a trap at the end.

# Joseph's Notes

Just like there is symmetry between cue/bury, channels/traps, etc. maybe there should be a symmetrical card ability to barrier? Something where you get a benefit if you plunge past it?

Possible we should change the flavor of barriers to be more like _responses_ to dives, with barriers blocking the dive as a subtype of the overarching new type. This will make mutually beneficial barrier effects, or barrier effects that don't slow down or stop the dive more in line with the overall type. Possible terminology: Gate, response, trigger, echo, riposte, parry, recoil

**Comment by ACG8** [comment]
I think the biggest takeaway here (as you allude to) is that we want to avoid effects that uniquely punish the diver.
