### ISSUE TITLE
New DUA

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#190]
![image](https://user-images.githubusercontent.com/3642851/43718215-99834610-994f-11e8-9653-681a26468e12.png)

I added the will bonus because it  looked a little weak to me. It is wordy now though.  I'd be fine with cutting the will gain -- it's just that compared with something like Reckless Duo, this loses the spot bonus.

**Comment by ANRTheBigBoy** [comment]
I still like my original suggestion. They lose 1, access outer. 

I access bottom is so annoying...

**Comment by ACG8** [comment]
Access bottom compensates for the free 0.83 value, in contrast to core dives with 0.33-0.5 value tacked on, since bottom doesn't have spot bonus. Is fine.

**Comment by millerj-tc** [comment]
Actually I forgot about that, I think outer is better too. The only reason Underworld Guide works is because it buries prepared cards first so it doens't challenge the user to play Memory (TM) about what was buried in what ordier.

**Comment by ACG8** [comment]
Ok, that is a fair point. Memory (TM) is not much fun.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/43749900-965a40f8-99bb-11e8-9f29-2f20e014be64.png)

Everyone okay with this?
