### ISSUE TITLE
New ID Shift

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#191]
![image](https://user-images.githubusercontent.com/3642851/43718367-0d2e3930-9950-11e8-8cda-301f5fa23da9.png)

Added the bury:prepare functionality because it looked weak and feels on flavor. Fine with cutting it if you think the baseline effect is good enough.

I also removed the dive chain functionality. We've mostly phased it out anyway.

**Comment by ANRTheBigBoy** [comment]
Great
