### ISSUE TITLE
New Hestia Trigger

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#194]
![image](https://user-images.githubusercontent.com/3642851/43718804-61522d86-9951-11e8-946c-aaeac35c6aa9.png)

Changed from "after you interpret your own dive" -- too restrictive.

**Comment by ANRTheBigBoy** [comment]
This is good now.

**Comment by millerj-tc** [comment]
Unassign yourself from cards you are cool with 👍
