### ISSUE TITLE
New Helm of Horns

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#195]
Feeds itself with card draw to prepare a card and has a useful ability tacked on to round it out.

![image](https://user-images.githubusercontent.com/3642851/43718988-06ca9082-9952-11e8-97a8-13a5ad34615c.png)

**Comment by ANRTheBigBoy** [comment]
Solid. 2nd ability is pretty generous. Go with 2/2

**Comment by ACG8** [comment]
Agree with @ANRTheBigBoy

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/43749728-e2ed40ba-99ba-11e8-861a-1bb0abd819bf.png)

Added to cardfile
