### ISSUE TITLE
Design New Cards

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#197]
After cutting cards, we should try to design 5-10 of each card type.

We are looking to:
- Fill out the will curve (especially 7, 8, 9, 10, and 11)
- Add incidental prepare effects to keep the board filled up
- Make sure to spread out archetype effects across card types so that no archetype is too dream phase reliant

**Comment by ACG8** [comment]
#217 - Blazing Herald (10 will Dream)
