### ISSUE TITLE
Winged Steed

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#198]
Giving some serious low to the ground card draw to dives. Not sure how good this is. Originally costed the second ability at [RDL], but Floof is [RDL] for i5, the EV on this seems less than that...

![image](https://user-images.githubusercontent.com/3642851/43751690-8d7c8952-99c3-11e8-8c03-8970852bfd6e.png)

**Comment by ANRTheBigBoy** [comment]
Make the 2nd ability dreamlucidcard?
Seems sweet.

**Comment by ACG8** [comment]
Agree with @ANRTheBigBoy
