### ISSUE TITLE
Determine deck-building restrictions

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#2]
We need to come up with sensible rules for building decks. Should be permissive but still encourage players to keep to their faction.

**Comment by millerj-tc** [comment]
Could be negative starting points:
- per out of faction card
- per out of faction card, plus scales with each additional faction
- rate per batch of out of faction cards (1-5= -X points, 6-10= -2X points, etc.)
- rate per batch out of  faction cards, plus scales with each additional faction

**Comment by ACG8** [comment]
Not sure it should be starting points; this requires players to tell each other how many points are in their decks at the beginning, and is another thing to keep track of. What about negative ending points? So at the end of the game, you reveal your deck and subtract the appropriate number of points.

**Comment by millerj-tc** [comment]
I addressed starting negative points vs end of game negative points on the raw points thread.

I think one hard deckbuilding restriction should be that you can't play a secret that isn't the same faction as your ID. This is because secrets are so important and so different between factions. Even if there is some secret variation within factions, you should have a decent idea of  which factions tend to have more valuable ones (elites) or crappy ones.

**Comment by ACG8** [comment]
Agreed (regarding secrets being associated with factions)

**Comment by millerj-tc** [comment]
Brendan and I were talking about deckbuilding restrictions. He felt like giving out negative points for out of faction cards was too punishing and would discourage innovation.

One idea we came up with was that out of faction cards give you scars instead (representing cognitive dissonance for subscribing to different ideologies). Then you give every faction cards that either punish other players with lots of scars or benefit them if other players have scars. This is a softer control on deckbuilding. The only thing with this is that we would have to be extremely careful about how/if we design cards that let people benefit from their _own_ scars.

**Comment by millerj-tc** [comment]
Abram has also suggested requiring a minimum number of in-faction cards of each ability type (channel, barrier, trap, etc.) in order to prevent decks that are too linear/reductive. This also means that each factions weaknesses in terms of card types (bad traps, bad barriers, etc.) will always have to be at least somewhat present in the deck even though they can also play superior out-of-faction cards if that card type is really important to their strategy.

**Comment by ACG8** [comment]
While having out of faction cards give you scars could work as an incentive, I am not sure it makes that much sense. It also disproportionately benefits IDs that can natively benefit from or remove scars (their own or other players'), such as the MC of horror or Convo.

Requiring a minimum number of in-faction cards of each ability type works, but if we add more ability types it could be a problem. Some cards also have multiple ability types (though I am not sure whether that is a problem or not).

One other idea is to use the system that Mage Wars has; you have a certain number of mind points to use when building your mind, and each card is worth some number of mind points (unrelated to game points). When building a deck, you must not exceed your mind points total. Out-of-faction cards cost twice as many mind points. The advantage to this is it provides a value we can use to help balance cards. The disadvantage is that it means putting one more piece of information of the cards (although it would be one that is only relevant during deck construction. Mind point values would be highly granular, probably ranging between 1 and 5, to avoid burdensome calculations.

**Comment by millerj-tc** [comment]
A variation on mind points:

Each card is worth a certain number of black and/or red deck points (0-2 of each). For each out of faction black deck point (or in faction red deck point) in your deck, you have to include that many points of vulnerability cards. Each red deck point in an out of faction deck counts as double.

Vulnerability cards are cards that either have no positive effect for the owner but are very valuable  if accessed by another player or have a very narrow effect (and are worth a lot of points for another player.)

Example:
A channel with some kind of minor effect worth 0 points to the owner, but 4 points to another player on access.

PROS
- New design space!
- There are certain effects that are cool, but so narrow that you probably don't want them in your deck. You just want proactive cards that make your plan work. Vulnerability cards are a cool way to give a player a reason to play a narrow card -- they have to! But it can still come with enough downside that it's a net loss for them. It just means that there are reasons to play interesting but underpowered cards.
- Strategically interesting -- choosing what vulnerability cards to include in your deck can be an interesting choice as some might help or hurt you more depending on the meta.
- Each vulnerability card can just be worth 1-2 points -- this means that you can't just hide a single 6 point vulnerability card in your hand where it can't be accessed. If you want to play a lot of out of faction cards you'll have to play a large number of vulnerability cards.
-  Red deck points let us create more powerful in faction cards that cost vulnerability cards even if you're playing that faction.

CONS
- Might be hard to balance

DESIGN CONSIDERATIONS
- More cards in your deck means it's harder to get to your secret. On average I think this is still worse for the player. I think you'd rather get your good cards more often than make one player pay one more to get your secret. However, certain archetypes may not be hurt by this as much as others. We may need to make vulnerability cards faction specific to make sure that they hurt the main plan of the deck adequately.

**Comment by ACG8** [comment]
I like this idea; however, I don't think we want to allow deck size to change too much. Maybe also include a deck size limit? Alternatively, I think Netrunner has a system where larger decks require more agendas; we could do something similar, requiring additional vulnerabilities for each card over a certain limit.

**Comment by millerj-tc** [comment]
Yeah I think one or both of those things would be fine. Depending on how
bad it is to play more than the minimum deck size we may only need a max
deck size for practicality reasons.

My hunch is that playing more than the minimum number of cards is pretty
bad because that's how it is in basically every CCG ever, but we can test
and see.

**Comment by millerj-tc** [comment]
Another idea: An end of game token that gives +X points for having the least "out of faction points" and an end of game token that gives -X points for having the most "out of faction points."

**Comment by ACG8** [comment]
Good idea; I like that it gives rewards and penalties relative to other players, not on an absolute scale. That creates a real metagame around figuring out how many OOF points other players are likely to have when constructing decks.

Something similar could be done for the sanity system #35 to make it softer. Give points to the player with the most sanity and take points away from the player with the least. Then players don't necessarily have to include cards they might not want, but doing so rewards them in game. Of course, you would then need some other way to prevent a deck full "selfish" cards.
