### ISSUE TITLE
Weird Planet

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#200]
I don't know if this is too weird. But it is called Weird Planet so...

![image](https://user-images.githubusercontent.com/3642851/43754167-00af4634-99cf-11e8-994a-5833ed0b234a.png)

**Comment by ANRTheBigBoy** [comment]
Why am I burying 2 and then drawing 2? I think you can remove that part and it's a lot more elegant. 

That said, a big will cost on a dream that you play in a small hand deck is a little annoying, but the baseline effect is pretty good so it's probably OK.

**Comment by millerj-tc** [comment]
Yeah, the bury two and draw two is trying to help with the small hand problem while limiting the ceiling. Basically what it means is that you can have 0-2 cards in hand before triggering this and still get max value (i9). It is a bit ugly though.

**Comment by millerj-tc** [comment]
I guess I could just stick a limit on it lol,

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/43780762-fe6410c4-9a20-11e8-9f36-e768f478e100.png)

**Comment by millerj-tc** [comment]
Although is this just a trap for players lol? Like what else are you playing in the same deck as this?

**Comment by ACG8** [comment]
Why does it need a limit? Is 3 more insight that game breaking? I would remove the limit and maybe increase the cost a little.

**Comment by ACG8** [comment]
*2 more insight

**Comment by ACG8** [comment]
(And it is difficult to get 11 anyway).

**Comment by millerj-tc** [comment]
The limit is prudent for expansions. What if there is an expansion/variant with more cards in the mind? I think it's just responsible design for a small team.
