### ISSUE TITLE
Chaos Ascendant

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#202]
Big money lucid

![image](https://user-images.githubusercontent.com/3642851/43752937-f16af412-99c8-11e8-9ea1-ac65b39efdb7.png)

**Comment by ANRTheBigBoy** [comment]
11 is a lot. Go with 9 I think.

**Comment by millerj-tc** [comment]
Can we bump the insight gain to 5/6? I want it at 11 for curve reasons.

**Comment by ACG8** [comment]
5/6 seems good to me.
