### ISSUE TITLE
Canny Astrowizard

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#203]
Another prepare dive

![image](https://user-images.githubusercontent.com/3642851/43753091-a9641d0a-99c9-11e8-98a8-389438750b80.png)

**Comment by ANRTheBigBoy** [comment]
Make it gain i1 and interpret inner so it's slightly more different from the core set one.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/43779156-3d8d6948-9a1d-11e8-8e66-c9c477bdb3ad.png)
