### ISSUE TITLE
Roar of the Arbiter

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#204]
Midrange sweeper!

![image](https://user-images.githubusercontent.com/3642851/43753318-c9a5e21e-99ca-11e8-9564-987493610cac.png)

**Comment by ANRTheBigBoy** [comment]
You can put "each other player". No need to make this symmetrical.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/43779181-55a64e14-9a1d-11e8-996c-668fc813b505.png)
