### ISSUE TITLE
Scars

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#21]
So I like what we're doing with traps and barriers mechanically, but I'm afraid the game is losing it's "teeth" a little bit. It doesn't feel scary to dive someone's mind in the current system. You might help them, but bad things rarely happen to you. I think other people's minds should sometimes feel scary.

What if we adapt tags from ANR? Hitting a Phantasm results in getting a phantom token, which cancels out a point but then also sticks around. Then certain cards will target players with x number of phantom tokens? That way we can create a trade-off for diving other players a lot even without punishing traps/barriers.

**Comment by millerj-tc** [comment]
We could simplify the game a lot like this:

Traps and channels are now all channels
Barriers are now "evoke" or something

Reverie channels and evokes are always optional
Phantasm channels and evokes must be activated (and often benefit owner or have weird trade-off that only the owner wants to make), unless the diver takes a phantom token

That way if you want to build a "trap" deck you just put in extra Phantasms and then some cards that punish phantom tokens

And since phantom tokens have inherent downside they can be fuel for high risk high reward strategies

**Comment by millerj-tc** [comment]
I'm going to recant most of this, I realized we could still design "toothy" traps and barriers with enough care.

I think **Blood-Engine Mech** from the Thieves Starter and **Encumbered Vision** from the Mercenary starter are really good examples. They benefit their owner, but they do so based on the decisions/deckbuilding of the other players. This makes them effective meta counters and they also feel like they are punishing and interactive -- even though the outcome is that they help their owner.

**Comment by ACG8** [comment]
So you are no longer interested in phantom tokens? A shame; I like the idea. I was thinking they could be called "scars" instead, though. Each scar is worth -1 point and encountering a phantasm gives you a scar (as with phantom tokens)

One thing that helps expand design space is adding new mechanics, so a scar mechanic would open up a lot of interesting cards.

**Comment by millerj-tc** [comment]
It's common to add new mechanics in expansions so I think we can save it
for a later expansion -- not all Phantasms are necessarily scarring

**Comment by millerj-tc** [comment]
Unless you think it's so compelling that it's worth the complexity (extra token type) to justify making it a core set mechanic?

**Comment by ACG8** [comment]
I think it is fairly compelling. Certainly it gives something more to work with, and if it is built into the phantasm type it would need to be in the core set.

**Comment by ACG8** [comment]
I am really liking this scar mechanic; I think it works much better than losing points. I am in favor of making it a part of the core rules. I've created a branch in which I re-imagine Doc Lock's deck with scars.

**Comment by millerj-tc** [comment]
Here are the downsides for me:
1. added complexity/components
2. pigeon holes all phantasms as scarring (Many Libertine phantasms aren't scarring, for instance, although we could add "no scar" text to those potentially)
3. hard to calculate someone's position (in points) if they have point tokens and scars floating around -- people have to think a lot during Destiny because of a similar interaction with damage and shields
4. not symmetrical -- phantasms give scars, but reveries and symbols do nothing?

We could make scars a part of the starter set but _not_ an intrinsic part of phantasms. Some phantasms (or other cards) could give scars, but not all of them would. This would solve bullet 2 and 4.

I think we absolutely need to solve bullet 3 though. Scars should remove point tokens. That way a player's current known "point position" is _always_ equal to their number of points tokens. If you're playing with 4 other people and trying to assess where everyone is without being too obvious/taking too long, you don't want to have to do a bunch of addition/subtraction between point tokens and scars. So each time you take a scar token, you lose a points token.

**Comment by ACG8** [comment]
If you lose a scar, do you gain a points token? Otherwise, removing scars is less important for players.

I don't see 4 as being an issue; symmetry between different types of cards is not important except to help players remember the rules.

If most phantasms are scarring with a few scattered exceptions, it might be worth just noting "no scar" on those as you suggest.

**Comment by millerj-tc** [comment]
One way to clean up the rules a lot is to forget about phantasms costing players points altogether. It was always a weird kind of arbitrary rule.

I know that therapists care about point loss right now on some cards. Could therapist cards generate scars and then care about those instead? In addition to caring about phantasms?

I could add scars into some of my phantasms in the other sets as well.

This way, accessing a card type never matters -- just its ability text. We can still have scars on phantasms.

I think this cleans up the game the most effectively.

Not a huge fan of phantasms always giving scars. But I haven't printed a therapist deck yet, so I could run my playtests without scars/point loss at all and then we could run some playtests with scars each way when you come back. I think the feel of the games will be instructive.

**Comment by ACG8** [comment]
Sure, I think we can get rid of the phantasm point loss rule. I think scars are a better consequence than straight up point loss (in many cases) because you can then have effects that can mitigate point loss from scars without also providing point gain once the scars are all removed. This will make abilities that cause point loss more impactful.

I'll edit my therapist deck to reflect the changes.

**Comment by millerj-tc** [comment]
Scars benched for the moment
