### ISSUE TITLE
The Unstoppable HMS Ingrid

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#210]
Bringing it back (old version interpreted a prepared card which was too good/annoying, but I'm on this top card kick now and I think it works)

![image](https://user-images.githubusercontent.com/3642851/43779902-06a56fd2-9a1f-11e8-9c44-252763f11f83.png)

**Comment by ACG8** [comment]
Raise the cost. I would say [w7]. A 100% guaranteed access is really, really, good.

**Comment by millerj-tc** [comment]
@ANRTheBigBoy What do you think about 7?

**Comment by ACG8** [comment]
Actually - would you be up for moving this to the prep phase? It keeps it just as unstoppable (if not more) and simplifies the trigger considerably.

**Comment by ACG8** [comment]
Though you do lose the dream decoy usage

**Comment by ACG8** [comment]
Which is not necessarily a bad thing, given how powerful it is already.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/43837995-cf237dee-9adf-11e8-8b80-cbd8c1b29702.png)

**Comment by ANRTheBigBoy** [comment]
I think vanilla pre-dive 1 will is already a good card, so this 2nd ability would have to cost a lot. Let's try 7.

**Comment by ACG8** [comment]
I agree. I might even go up to 8; this card is almost strictly better than Sea of Gold without the second ability. Alternately, what if the first ability cost [w1] (so you can't use the will the same turn you get it)?

**Comment by ACG8** [comment]
Or perhaps give it a bury cost? Bury a dive to gain [w1]?

**Comment by millerj-tc** [comment]
You (@ANRTheBigBoy) said the After Prep base value should be .5 of a core dream. So this is exactly on curve for what you get for free.

@ACG8: I don't think Sea of Gold is a good comparison. That's an old card that isn't up to current standards and hasn't been re-evaluated in a long time.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/43870512-751d321e-9b3d-11e8-95ce-78147de048f9.png)
