### ISSUE TITLE
Update Ij, any remaining reveal middle card effects

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#213]

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/43814624-ed336a32-9a90-11e8-8c2c-0162c7c4e45f.png)

**Comment by ANRTheBigBoy** [comment]
This is very good. Maybe make it 1 and 1 instead of 2 or 2?

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/43843589-8b063d3c-9aed-11e8-98ae-7e6fd01a2f7d.png)
