### ISSUE TITLE
More Mouse effects

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#214]

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/43814672-33f3c674-9a91-11e8-8804-1bdafa478f81.png)

![image](https://user-images.githubusercontent.com/3642851/43814676-36dc3e16-9a91-11e8-805c-b7b5bd612e13.png)

**Comment by ANRTheBigBoy** [comment]
These are cool. Bruhn is hard to evaluate, but probably fine.

**Comment by ACG8** [comment]
Forest Shaman is way too good. You are almost guaranteed to get a dream, and get [i1] and [w1] on top of that. Remove the will and insight bonuses; the array of choices should be enough.

**Comment by millerj-tc** [comment]
A core set dive gives you a spot bonus and a spot bonus on interpret. The w1 i1 accounts for that. Whether or not a higher chance of hitting a dream is good is contextual. Sometimes it's more important to disrupt that player's board. Sometimes the other player's dreams won't be that good for you. I think it's hard to demonstrate that it's categorically too good. If I'm playing a handless deck and get to choose between Lucid, Dive, and Bubblegum Diner, I think that's substantially worse than hitting a prepared card and disrupting their board.

Also, we should err on the side of letting OP things through to test the design space.

**Comment by ANRTheBigBoy** [comment]
I think you can remove the symmetrical card draw (or reduce it to 1 card). That way people can play around the Shaman by not holding stuff.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/43870482-468ce96c-9b3d-11e8-9dd4-02861553d859.png)
