### ISSUE TITLE
The Slumbering God

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#216]
![the slumbering god](https://user-images.githubusercontent.com/10094820/43982769-1da2d4ea-9cbd-11e8-9a9d-ea23bd68564a.jpg)

Heavy disruption for dream-centric minds.

**Comment by millerj-tc** [comment]
I like this. It's hard to evaluate. I think with this and RSS we do need to
be careful of creating some kind of "soft lock" where you can skip the
dive/dream phase too often.

I think testing it at this rate is probably fine? How easy is it to recur
an effect like this right now? Maybe draw your whole mind, Rippo, something
else that draws more cards?

**Comment by ACG8** [comment]
Actually, this brings up an interesting rules question. If you skip a phase, do effects that happen "after the ___ phase" still happen? After all, a Lucid that triggers after one of your cards is interpreted never triggers if none of your cards are interpreted. If a phase never happens, do Lucids that trigger after the phase still occur?

To be clear, I don't think there is an obvious answer from the rules; I think this is something we need to decide.

**Comment by millerj-tc** [comment]
I think in most ways I would think of it, yes, those effects would still trigger.

Like, if a card says skip the dive phase, we don't suddenly lose ourselves in the Twilight Zone and not know what phase is next -- we know we go to the dream phase. So skipping the dive phase doesn't mean that we have no point of reference, just that in this instance we didn't do anything during that phase.

In terms of a physical analogy, if there are 4 sequential spaces (1 -- 2 -- 3 -- 4) and I say "go through 1 and 2, skip over 3, and land on 4"  and then asked you "are you after 3?" the answer would be "yes" even though  you skipped it.

That's my take on it anyway.

**Comment by ACG8** [comment]
Obsolete due to orb lucid changes. Persistent "skip dive phase" is way too strong, and it doesn't work as a burst effect (since lucid is after dive). Closing.
