### ISSUE TITLE
Basilisk Nerf

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#221]
Increase cost or decrease cards drawn.

**Comment by ANRTheBigBoy** [comment]
Maybe both? Draw 2 and add another [b] to the cost.

**Comment by millerj-tc** [comment]
Cf with Greed of the Demon Prince -- that gets a full dream of value as
baseline. Valkyrie gets .66. Don't see why this one should get less on top
of a cost increase to the second part.

**Comment by ANRTheBigBoy** [comment]
Because it feeds itself. But go ahead and just do the cost increase if you want.
