### ISSUE TITLE
Positional disruption dives

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#229]
Rework to remove positional disruption

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/44525619-1c56cd00-a6a7-11e8-8813-9be5d8179e6e.png)

![image](https://user-images.githubusercontent.com/3642851/44525622-1e209080-a6a7-11e8-8c1a-8d7ba3284396.png)

![image](https://user-images.githubusercontent.com/3642851/44525625-2082ea80-a6a7-11e8-8605-35a023085b48.png)

![image](https://user-images.githubusercontent.com/3642851/44525627-224cae00-a6a7-11e8-804d-22b8bad47992.png)

Removed Ij from the game temporarily -- there are too many dreams and dives relative to lucids anyway.

**Comment by millerj-tc** [comment]
Actually, could Underworld guide just hit other players with the first ability?

**Comment by millerj-tc** [comment]
It could also make people bury their top card.

**Comment by ANRTheBigBoy** [comment]
Underworld guide seems weak. It should just hit other players.
Whale city can also just hit other players.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/44559992-07178800-a713-11e8-8e7f-ac03c4198872.png)

![image](https://user-images.githubusercontent.com/3642851/44560004-13034a00-a713-11e8-88a5-1c2ed64eb7e1.png)
