### ISSUE TITLE
Buff Dream Vacation

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#230]
Dream vacation is way below curve right now. Suggested buff is to reduce will loss to 1. Alternately, we could mirror the handless cards and give a small bonus unconditionally and the rest if you dump your will.

**Comment by ACG8** [comment]
![dream vacation](https://user-images.githubusercontent.com/10094820/44501968-00c2d680-a655-11e8-8de2-0dcdee2daccb.jpg)

**Comment by ACG8** [comment]
![dream vacation](https://user-images.githubusercontent.com/10094820/44502044-48496280-a655-11e8-96ea-be04d60f8f00.jpg)

**Comment by ACG8** [comment]
![dream vacation](https://user-images.githubusercontent.com/10094820/44502231-27cdd800-a656-11e8-98d4-0c5a69b35318.jpg)

This is more in line with how all the other hand/will-less cards work.

**Comment by millerj-tc** [comment]
Corrupted and Cleanser give you a spot bonus + the option to gain more in exchange for all of your secondary resource.

![image](https://user-images.githubusercontent.com/3642851/44525914-17dee400-a6a8-11e8-8690-110e251cc3c8.png)

**Comment by ACG8** [comment]
If you lose all will, you should at least gain seven cards.

Burying your hand is a lot less painful than losing all your will, because card costs always involve losing the resource whereas will refreshes each turn.
