### ISSUE TITLE
Nerf Danse Macabre

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#231]
With the recent changes to the hand denial cards, Danse Macabre is super painful to hit. I suggest we give it a similar treatment.

**Comment by ACG8** [comment]
![danse macabre](https://user-images.githubusercontent.com/10094820/44502123-9cecdd80-a655-11e8-99da-4ad117d0123e.jpg)

**Comment by millerj-tc** [comment]
Looks good
