### ISSUE TITLE
Alien Cube

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#232]
Remove extra text and change cost to 7

**Comment by millerj-tc** [comment]
I dunno, @ANRTheBigBoy, then you're paying 7 for an i8 swing? That's better than Hod and Hod does less work than this to keep you in the game. It's only worse than Hod when you have 5-8 will and even then it's ONLY better if that's the ONLY thing you want to spend will on.

**Comment by ACG8** [comment]
For reference:

![alien cube](https://user-images.githubusercontent.com/10094820/44632996-48de4380-a94a-11e8-8b81-cc6c597db592.jpg)

**Comment by ACG8** [comment]
I think it is ok to have diminishing returns for additional effects on cards. The disadvantage of Hod is that you have to use will to get any benefit out of it. This gives benefit even with no will, so I don't mind so much if the extra effect is more expensive than it might be on another card.

**Comment by ANRTheBigBoy** [comment]
Ya actually you are right, although Hod SHOULD be worse than any card that has a fixed cost, since flexibility should come at a cost (see X-spells in MtG).

How about make it 8 and we gud? :P

**Comment by ACG8** [comment]
I'd be fine with 8.
