### ISSUE TITLE
Helm of Horns Nerf

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#233]

**Comment by ACG8** [comment]
![helm of horns](https://user-images.githubusercontent.com/10094820/44632969-c9e90b00-a949-11e8-81e8-a3a42ed2d579.jpg)

Greater flexibility but no built in spot bonus. Also fantastic when going last.

**Comment by ANRTheBigBoy** [comment]
This is cool.

**Comment by millerj-tc** [comment]
Do both have to be tied to a cost? Seems like it would be just fine if the first one was free. Makes the card a lot cleaner too.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/44694671-77d0e400-aa34-11e8-82ef-832b2160f892.png)

**Comment by ANRTheBigBoy** [comment]
This is still strictly better than every horse lol.

**Comment by millerj-tc** [comment]
Maybe horses aren't good enough. Could also do this:
![image](https://user-images.githubusercontent.com/3642851/44695597-92f22280-aa39-11e8-92c7-efaade1fc8ed.png)

**Comment by ANRTheBigBoy** [comment]
Nice, I like this.

**Comment by ANRTheBigBoy** [comment]
I guess horses just trade a spot bonus for a card (when compared to basic actions). That's not actually very good lol. 

I think removing the will cost from horses is probably a good idea. They don't need it anymore and it makes them cleaner.
