### ISSUE TITLE
Memories set ablaze

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#235]
"if no cards in hand"

**Comment by ACG8** [comment]
![memories set ablaze](https://user-images.githubusercontent.com/10094820/44632904-b2f5e900-a948-11e8-9e7e-7cb608edbe52.jpg)

**Comment by ANRTheBigBoy** [comment]
empty hand vs. no cards in hand? We gonna standardize to this?

**Comment by ACG8** [comment]
I think we should; empty hand is more concise.

**Comment by millerj-tc** [comment]
We already have an issue for this card -- I mistakenly put it in twice.
