### ISSUE TITLE
Sly Fox Planet tweak

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#239]
Too swingy/hail mary

**Comment by ACG8** [comment]
Proposal:

![sly fox planet](https://user-images.githubusercontent.com/10094820/44633177-f3576600-a94c-11e8-84ac-ad987858d60d.jpg)

Sort of a balance theme (harmony with nature?). The paid ability is good, but makes it much harder to use the unpaid part the more you use it. The unpaid ability can work well in pure rush decks (willless/handless), but only if you really, really commit.

**Comment by ANRTheBigBoy** [comment]
Hand size is confusing for people who have played other games where hand size refers to maximum hand size. Should be "the number of cards in your hand"

It should be noted drawing this card in your opening hand makes things weird :P

**Comment by ACG8** [comment]
Not that weird, I think. Sure, you can easily trigger the second part, but it's no better than a card like the cleanser in your opening hand.

**Comment by ACG8** [comment]
![sly fox planet](https://user-images.githubusercontent.com/10094820/44633537-35cf7180-a952-11e8-9ee5-1a6430388217.jpg)

**Comment by millerj-tc** [comment]
I don't think I'd ever play it because it hurts my brain, but I'm sure there are players who would want to.
