### ISSUE TITLE
Memories set ablaze rework

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#241]

**Comment by millerj-tc** [comment]
I like this design because even though the paid ability is below curve, it adds the functionality of allowing the Eyyy deck to profitably control their hand size.

![image](https://user-images.githubusercontent.com/3642851/44630225-c3459e00-a91f-11e8-9c3e-2914bf3f340e.png)

**Comment by millerj-tc** [comment]
Although maybe the ability orders should be reversed so that you can use the paid ability to meet the i15 requirement?

**Comment by millerj-tc** [comment]
Or we could attach the disruption to the paid ability (maintaining the i15 condition.)

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/44630243-01db5880-a920-11e8-93e1-5f235f798928.png)

**Comment by ACG8** [comment]
I like the second one more.

**Comment by ANRTheBigBoy** [comment]
I'd find it hard to take this because it's not THAT much better than Monument. Can we make it a little more exciting?

**Comment by millerj-tc** [comment]
Here's @ACG8's from the duplicate thread:
![image](https://user-images.githubusercontent.com/3642851/44638526-ea7e8880-a97c-11e8-9908-2f113d33275a.png)

**Comment by millerj-tc** [comment]
I think we should probably ditch burying "at random"?

Basically, even if you don't care what particular cards are in your hand, "at random" adds a process, so it probably takes longer on average?

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/44694651-53750780-aa34-11e8-9eb3-3a2e6cd083bd.png)
