### ISSUE TITLE
Castiehl rework

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#242]
Too much text

**Comment by millerj-tc** [comment]
I like that because it's subtle last player advantage: you have more info about who used a dive during their turn and so can slightly make your chances better by targeting them. The payoff is pretty big so it seems like it adds a lot of T1 variance. Added a [r] cost to make it pretty easy to activate but still a little bit of work.

![image](https://user-images.githubusercontent.com/3642851/44629627-be7cec00-a917-11e8-8f09-bb867a6525b4.png)

**Comment by ANRTheBigBoy** [comment]
Seems like it can be any card, not just a dream that you bury. Still solves turn 1 problem. Top card dives don't need MORE hoops for you to jump through...

**Comment by millerj-tc** [comment]
No, because you can draw a card on T1 by making this your middle card. This is still a great value card early on because I think you care less about disruption early on. People have less control over what they put down so it probably doesn't matter as much.
