### ISSUE TITLE
Bruhn rework

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#243]

**Comment by millerj-tc** [comment]
I like the idea of keeping a little bit of hand-interpret in the game longer to see how it feels. We need a critical mass of those effects to evaluate them. Cf this Bruhn with Forest Shaman

![image](https://user-images.githubusercontent.com/3642851/44629713-c9844c00-a918-11e8-9445-890c51ebec3e.png)

![image](https://user-images.githubusercontent.com/3642851/44629717-db65ef00-a918-11e8-999c-008e278755ec.png)

**Comment by ANRTheBigBoy** [comment]
These cards seem so bad to me...

**Comment by ACG8** [comment]
They are good because they give the best chance of finding a good card, especially against players with a large hand size.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/44694566-cdf15780-aa33-11e8-9153-32f0d2c29daf.png)

**Comment by ANRTheBigBoy** [comment]
I find these really really hard to figure out. Maybe just put them in my deck next time and force me to play with them lol.
