### ISSUE TITLE
Confusion in Mushroom Land rework

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#244]

**Comment by ACG8** [comment]
Proposal:

![confusion in mushroom land](https://user-images.githubusercontent.com/10094820/44633251-382fcc80-a94e-11e8-864f-0158e3fac683.jpg)

Explanation:
You can swap your dive and possibly get another dream/lucid out, letting you dive without sacrificing a prepared card slot.

**Comment by ANRTheBigBoy** [comment]
This seems weak. The burst ability should give you something else too.

**Comment by ACG8** [comment]
Possibly. One thing I noticed about "prepare your top card" is that it feels really bad when it turns out to be a dive (or a lucid, for burst effects).

**Comment by ACG8** [comment]
![confusion in mushroom land](https://user-images.githubusercontent.com/10094820/44633573-e6d60c00-a952-11e8-9537-06ac3c1e2511.jpg)

**Comment by ACG8** [comment]
![confusion in mushroom land](https://user-images.githubusercontent.com/10094820/44633582-f5242800-a952-11e8-81d2-24cf49c459e5.jpg)

**Comment by ANRTheBigBoy** [comment]
It doesn't need the draw a card. Make it "Prepare your top card or gain 2". Remember you are rigging your top card.

**Comment by ACG8** [comment]
![confusion in mushroom land](https://user-images.githubusercontent.com/10094820/44752695-701b4900-aae1-11e8-8ffe-691bd6d8e456.jpg)
