### ISSUE TITLE
Under Frog Lake Rework

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#247]
Bury cards to make others lose will

**Comment by millerj-tc** [comment]
This is better than Wrath, but I think it's still okay?

![image](https://user-images.githubusercontent.com/3642851/44630160-f6d3f880-a91e-11e8-9f3f-fadfd02a72d9.png)

cf

![image](https://user-images.githubusercontent.com/3642851/44630166-05221480-a91f-11e8-8b92-c0c24b59e6eb.png)

**Comment by ANRTheBigBoy** [comment]
Really strong. Wrath is already a very strong card.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/44639011-3af6e580-a97f-11e8-89e3-59aad9bcbdcb.png)
?
