### ISSUE TITLE
Retyping "dive" cards

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#25]
Regardless of what we decide to do about dive chaining I think we should re-type these.

From highest to lowest preference:
Aspect
Form
Symbol

Image
Abstract
Icon
Vision
Dream

Brain
Facet
Thought
Wit

**Comment by ACG8** [comment]
I would go for Symbol or Motif.

**Comment by millerj-tc** [comment]
Sounds good, let's go with Symbol.
