### ISSUE TITLE
Dream Phase terminology

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#250]
We need a term for the interpretation of dreams that happens in the dream phase.

Interpret actually works, as long as it is made clear that only interpretations during the dive phase grant spot bonuses. Though this poses a problem if dives are interpreted during the dream phase (or lucid phase), so having a separate term is probably clearer ("dream text happens when any player interprets the dream or ______ the dream during the dream phase").

I was thinking maybe "resolve". It has the right connotations both for mechanics and theme (resolving a dream is like figuring out what it was trying to tell you). The term doesn't have to apply just to dreams either; it could apply to any effect executed not as part of a dive-phase interpretation.

**Comment by ANRTheBigBoy** [comment]
Manifest? idfk lol

**Comment by millerj-tc** [comment]
I think this is just a demonstration that the interpretation flow chart has gotten too complicated. I started to map it out and found it too exhausting and gave up.

I think we can simplify the rules greatly by eliminating corner cases that are often strategically incorrect. IE Say you can only interpret cards during their named phase with a single exception: You can interpret an opponent's dream during your dive phase. Then we don't need to worry about all this shenanigans.

During the dive phase you interpret dive cards (and subsequently, opponent cards).
 - We could even have a "basic dive reminder card" that says "Interpret another player's prepared card or top card." that beginners to have in front of them to remind them that they can do that as a "base game action" if they don't have a dive card from their mind.

During the dream phase you interpret a dream card.

During the lucid phase you interpret a lucid card.

And we can still make card effects that violate the general rule, if you really want to get value out of two lucid effects we could stick  "interpret a lucid from among your prepared cards" as a dive ability.

**Comment by millerj-tc** [comment]
In Discord we resolved to use different verbs for different card types

We are holding off on whether to allow non-dive cards to be used during the dive phase.
