### ISSUE TITLE
Remove will cost from horses

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#251]

**Comment by ACG8** [comment]
![horsepower](https://user-images.githubusercontent.com/10094820/44753021-6e9e5080-aae2-11e8-8e24-6eb20df577c4.jpg)
![nightmare](https://user-images.githubusercontent.com/10094820/44753022-6e9e5080-aae2-11e8-97ba-a9ac5edda727.jpg)
![painted thunder](https://user-images.githubusercontent.com/10094820/44753023-6e9e5080-aae2-11e8-951a-1a93274ac8a2.jpg)
