### ISSUE TITLE
Complete iron Valkyrie cycle

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#253]

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/45064895-f7d1fc00-b07b-11e8-86eb-063f7ce11cbb.png)

**Comment by ANRTheBigBoy** [comment]
Make it i4 and it's fine.

**Comment by ANRTheBigBoy** [comment]
So if you hit all conditions let's compare:
Valk is 3 pts for no cost
Greed is 2 will 2 pts prereq 3 will
This is 5 pts for 2 cards. 

I guess it is fair... 5 just seems like so much but the math checks out OK.
