### ISSUE TITLE
What Goes Up...

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#258]
![image](https://user-images.githubusercontent.com/3642851/44970059-7e1ffe00-af15-11e8-8b85-592641d4e348.png)

**Comment by ANRTheBigBoy** [comment]
This passive is too strong for rush. Passive unconditional i2 is something I stayed away from on purpose.

**Comment by millerj-tc** [comment]
So let's say you get this T1. The average game is five turns. It's i5 better than Shelter, total. (Just looking at the passive right now). You think that someone at the table won't net roughly i5 from drawing four extra cards? Considering both bury costs and the flexibility afforded by having more cards in hand?

**Comment by millerj-tc** [comment]
Could also make the card draw symmetrical while keeping the passive asymmetric like this:
![image](https://user-images.githubusercontent.com/3642851/44995156-5c4f6700-af67-11e8-959f-00247b5bcb0f.png)

**Comment by ANRTheBigBoy** [comment]
I like this better, but the burst is too good. Make it 2 cards. Making each other playing lose 3 for no cost is already above curve. I get that they wont always lose 3, but average-case this is really nuts.

**Comment by millerj-tc** [comment]
What do you think @ACG8 ? I think the burst is okay, mostly because you're balancing it out by giving them options with the card draw the passive provides.
