### ISSUE TITLE
New potential core set Lucid

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#263]
Dive phase lucid with a medium bury cost or typed-bury cost to replace Deluge or Floof

**Comment by ANRTheBigBoy** [comment]
I kinda wanted to leave dive phase ones out of the core. They are better to introduce after the first game. 

I think Deluge is the one we should move to draft set. Floof is fun for the first game. 

New lucid
End of Round: Gain w1
-----
[bury][bury][bury]: Gain w3

**Comment by millerj-tc** [comment]
Since I have trouble remembering to trigger them and I've played like three times I think it might be helpful to try having one in the core to see if that helps people remember.

**Comment by ANRTheBigBoy** [comment]
The reason you just cited is exactly why I wanted to NOT put them in core.

**Comment by millerj-tc** [comment]
I thought we agreed that missed triggers aren't a big deal? Like, imagine if 3 people are playing who have never played before. If even one person remembers during the first game, everyone else will be like "oh yeah, I should remember to pay attention to that." Then they'll pay attention during subsequent games. All three players are less likely to remember when there's a ton of extra stuff to think about once they start drafting.

That's my take.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/44994838-1b0a8780-af66-11e8-891b-5e2cee676100.png)

**Comment by ANRTheBigBoy** [comment]
When do I get the spot bonus?

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/45039232-c8de6a80-b028-11e8-9219-b8233eba2d86.png)
