### ISSUE TITLE
Her True Colors

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#265]
The burst is strong because:
- The passive is weak for a draft card
- It's tricky to pull off since you need a prepared lucid to trigger the burst and you need to bury the other two, so you can't do the thing where you prep two lucids to pop it.
- It's a pretty comparable rate to the burst effect of Cosmic Triad which dishes out 2.5 dreams worth of value for a rainbow bury. Impressive Display gives you 2 dreams for triple dream bury. This is 2.66 dreams of value with a much harder condition.

![image](https://user-images.githubusercontent.com/3642851/44996354-24e3b900-af6d-11e8-981c-30b814c6905b.png)

**Comment by ANRTheBigBoy** [comment]
You need to draw all your lucids to pull it off. This seems totally fair.
