### ISSUE TITLE
Change Maw in Core?

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#271]
Introduce player's to spot icon in text box. I'm pretty strongly in favor. I'd like it somewhere if not here.

![image](https://user-images.githubusercontent.com/3642851/45004397-c5f46300-afb1-11e8-9a14-433a02a6d1a2.png)

**Comment by ACG8** [comment]
Seems like a straight nerf. Which isn't necessarily a bad thing; this card is included in a lot of decks.

**Comment by ACG8** [comment]
Also, does the word "any" need to be there? Since * implies any by definition.

**Comment by ANRTheBigBoy** [comment]
I'd rather keep this the same and introduce it on the new lucid I think.

**Comment by millerj-tc** [comment]
Maybe this card?

![image](https://user-images.githubusercontent.com/3642851/45011630-2a76e880-afd9-11e8-84c7-f276e7b1691f.png)

**Comment by millerj-tc** [comment]
It's meant to be a cleaning wording of Silhouette's condition

![image](https://user-images.githubusercontent.com/3642851/45039169-a3e9f780-b028-11e8-9426-46396043dea5.png)

**Comment by ANRTheBigBoy** [comment]
Right, so do I get this at the end of the phase, or at the time of access? Just a rules question.

**Comment by millerj-tc** [comment]
After your turn, but not after everyone? When do you get Moment? :P

**Comment by ANRTheBigBoy** [comment]
Ya that's fine.
