### ISSUE TITLE
Design some new Knowledge of Shadows type cards

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#275]
Cost will/have an insight requirement and a cards in hand threshold requirement. Combos well with bury costs if you time them right.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/45066188-c0b31900-b082-11e8-8204-f2fcb76308cd.png)

**Comment by ANRTheBigBoy** [comment]
Don't need the "and".

**Comment by ACG8** [comment]
Yeah, just do newline, new sentence.

**Comment by millerj-tc** [comment]
That's the common way of writing it:
![image](https://user-images.githubusercontent.com/3642851/45300702-b2c32500-b4d4-11e8-98bd-cfe433fe2ef4.png)

Also some testers have gotten confused with excessive use of newline (wondering if the newline means something mechanical.)

I think we need to figure out a standard for when we use "and," newline, etc. Probably by showing some samples to a variety of testers and asking what they think. Maybe also a Carolina question.

**Comment by ACG8** [comment]
I would propose separating effects with newlines as much as possible as the standard. Gain effects (gain points/will/cards) can be gathered together.

**Comment by millerj-tc** [comment]
I don't think it's something there's a ton to theory craft about. I think we just need to mock up some samples and show them to 20 people and see what the response is. (And consult a professional.)
