### ISSUE TITLE
"Limbo" for card effects

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#28]
One thing I was thinking is that currently we have dive cards resolve after the current dive resolves. But once you channel something you bury it. So you may be in a situation where you are executing a card dive, but forget the instructions and have to awkwardly try to find it in your deck (it may have moved during the dive).

We could have a rule that channeled effects remain face up in front of you ("limbo") until they resolve and then are buried to avoid this annoyance. I've written another fix into the rules currently which you can read in the rules clarifications section about how to handle card dives.

**Comment by ACG8** [comment]
Sure, that makes sense. We could do the same thing for traps, too.

**Comment by ACG8** [comment]
Yes, I think making it an explicit rule that cards to be buried (or cued) are set to the side in the meantime is better than the suggestion that the card be buried face up and sticking out; that does not seem like a smooth gameplay experience to me.
