### ISSUE TITLE
Burst Costs -- in core and in general

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#280]
Tester had a difficult time planning around burst costs because of their weird timing

We should aim to have lucids (especially in core, but also in draft) have burst effects that either:
- Have zero cost and are categorically helpful (limit awkward interactions where Ki'Ix'To burst leads to ruining your own Intergalactic Planetarium, for instance.)
- Have a very high cost and a very high payout so that players are very likely planning around paying the cost.

---

We also discussed moving the burst bonus to happen on interpretation, but Abram pointed out that if it gives any kind of usable resource (cards or will), then it represents a huge early advantage if you get an early lucid (both the resource edge and the passive edge.)

If we want to make this change, we could try and design some burst effects that:
- Are enough of an advantage that you are incentivized to replace lucids
- Don't snowball the game.

Here are some ideas:
- If you use a lucid you gain the first player token
- When you use a lucid you get to draw three cards and bury two of them
- Gain any two spot bonuses, but not two of the same (this can give you spendable resources, but not a lot, and you've almost certainly lost out on other spendable resources because you got your dream or dive taken.)

Even if you don't want this change, brainstorm some other ideas just to make sure we have a good sense of what it *could* be if it winds up being necessary.

**Comment by ACG8** [comment]
After playing with lucids a bit, I don't feel as strongly against moving burst to interpretation as before. It would be a shame to lose quest lucids, but I think those can still be somewhat covered by dreams. I would not even be opposed to standardizing burst effects, freeing up more space for the passive effects.

As far as burst effects go, I like the double spot bonus idea. Are these intended to be standardized effects, or just examples of the power level of customized burst effects going forward?

**Comment by millerj-tc** [comment]
They're just brainstorming for either
