### ISSUE TITLE
Mexxos Rework?

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#281]
Mexxos has a ton of text to basically be a sometimes better Monument which already isn't that great a card.

**Comment by ACG8** [comment]
Proposal:

![mexxos thought extractor](https://user-images.githubusercontent.com/10094820/45391720-beecd680-b5e9-11e8-9a73-80f0a728e8f4.jpg)

Reasoning:
Preserves some of the theme while removing the interaction (making it more compatible with simultaneous dreaming).
