### ISSUE TITLE
Preconstructed decks

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#285]
Going straight from a core game to a draft can be hard for new players. We should make some preconstructed decks in various archetypes so that people can play a precon game and see how those decks match up against each other and what cards go in them.

**Comment by ANRTheBigBoy** [comment]
Could make each one 6 core cards + 6 draft cards. 

I'll work on some.

**Comment by ACG8** [comment]
Here is a Handless Deck:

**Dreams**
_Corrupted By Ruin_
_The Cleanser_
_Eyyyyyy_
City of Edges

**Dives**
Maw of the Cloudfish
Charge of Israfel
_Grant Says No_
_Down the Rabbit Hole_

**Lucids**
Moment of Understanding
Shelter from the Dark
Ghost of the Galaxies
_Doomsday Project_
