### ISSUE TITLE
Top card Fixes

### ISSUE THREAD

**Issue by ANRTheBigBoy** [ACG8/Lucid#288]
Making a new issue to focus on this. 

Right now the best executed Top card interpreter we have is Maw of the Cloudfish. It synergizes with all the top card lucids, while being a solid card on its own and simple enough for the core set. This got me thinking that we should focus top card accesses on two types:

1. Base prepared card interpret effect with a cost/threshold that lets you interpret a top card. 
2. Cards with the potential to interpret multiple top cards (maybe just like 3 of these). (See Intergalactic Journey)

#1 This solves Anandas concern while also making all the top card dives playable even without synergies. This also helps the top card lucids, since you can take the top card dives without going all-in, and then slot in the lucids later if you got 2-3 of the dives they work with (since you can always also play Maw).

#2 is interesting because it gives you an option to commit more heavily to top cards if you want to, and makes it so there are cards in the draft pool you can count on other people not taking incidentally if you are going for that kind of theme.

**Comment by ANRTheBigBoy** [comment]
![image](https://user-images.githubusercontent.com/41978055/45605280-82621600-ba01-11e8-9985-97260747e7bb.png)
![image](https://user-images.githubusercontent.com/41978055/45605285-8d1cab00-ba01-11e8-93f2-d2192ea296f1.png)
![image](https://user-images.githubusercontent.com/41978055/45605290-986fd680-ba01-11e8-839f-1572bf9c7848.png)

**Comment by millerj-tc** [comment]
These seem undercosted, maybe add a nonspecific bury cost to each?

**Comment by ANRTheBigBoy** [comment]
What is the value of a top card access? Something like 2.75 insight? 
Compare to Adorbs couple. I think it prices out fairly. Having to bury specific types is a bummer (and the stronger ones specify dive, which you only have 3 of since this is in play.)

**Comment by millerj-tc** [comment]
Let's just compare apples to apples, look at Maw.

Do you think burying two cards of a specific type is roughly the same as exhausting 5 will?

**Comment by ANRTheBigBoy** [comment]
I think so? You get the will back. You don't get the cards back. It's an easier threshold but most costly.

**Comment by ANRTheBigBoy** [comment]
Also these are allowed to be a little bit better than Maw since they are draft cards.
