### ISSUE TITLE
"You may" on Lucid cards

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#29]
Lucid effects seem implicitly optional to me; they are in your hand, so to use them you have to reveal them anyway. Should we make it a rule of card wording that we drop the "you may" from lucid effects and assume that the use of the Lucid card is always optional (and therefore the effect is mandatory once activated?)

For example, this would mean changing the text of _Birthdays Mangle Wax_ from

> Lucid: When a player gains the first player token, you may give them a scar.

to 

> Lucid: When a player gains the first player token, give them a scar.

I've already used this convention on most of my cards, and I notice you have on yours; it might be a good idea to make it official and also have a wiki page listing card design conventions (or just merge it with the card rules page). I notice you already use this convention on your cards.

**Comment by millerj-tc** [comment]
Sounds good
