### ISSUE TITLE
Simple top card dive

### ISSUE THREAD

**Issue by ANRTheBigBoy** [ACG8/Lucid#291]
A lot of our heavy complexity cards are top card dives. I thought I'd make a simpler one. 

![image](https://user-images.githubusercontent.com/41978055/45919789-a0e06b00-be60-11e8-9fc9-a2e19ff7b481.png)

This could even be made into a cycle. That would:
1. Reduce average dive complexity
2. Support top card archetype while keeping it interactive
3. Provide some more generalist dives that anyone can feel reasonably happy slotting over a core dive.

**Comment by ANRTheBigBoy** [comment]
Actually, I wonder if this is a little weak. You trade the core dive extra spot bonus for spot flexibility and not triggering reverse spots, but I'm not sure that's enough better for a draft card (synergies aside). Maybe these should gain 1and1 rather than just 1. Thoughts?

**Comment by millerj-tc** [comment]
Print it strong so people use it, then dial back if necessary. I think a
small buff is okay

**Comment by millerj-tc** [comment]
Got it
