### ISSUE TITLE
Midrange Cards

### ISSUE THREAD

**Issue by ANRTheBigBoy** [ACG8/Lucid#297]
Here are 3 cards that help midrange close out the game before big will kicks in, but which can't be used well by rush.

![image](https://user-images.githubusercontent.com/41978055/46265349-45128380-c4eb-11e8-8ec5-ce98d58770f1.png)

**Comment by millerj-tc** [comment]
We should also design some "exhaust all" and other midrange designs to see what #FeelsGood and won't be drafted by control/will be dramatically less good in their deck.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/46268047-f0c4cf00-c4fd-11e8-984f-1451e94cc051.png)

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/46268058-0934e980-c4fe-11e8-808e-5c88a29c7d0c.png)

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/46268134-75175200-c4fe-11e8-9049-c88268322ef4.png)

**Comment by millerj-tc** [comment]
Buff mixed resource lucids

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/46268657-4484e780-c501-11e8-8320-99372fbd63d5.png)

**Comment by ANRTheBigBoy** [comment]
Scooter ride is a sweet idea, but the numbers are too good. Imagine it's turn 2-3 and you have just 3 will. You gain 6 points, 2 will, and draw 2 cards. Pretty insane... Tone the numbers down a bunch and it's great!

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/46268833-89f5e480-c502-11e8-8a2f-b5afa90ba477.png)

**Comment by millerj-tc** [comment]
@ANRTheBigBoy : edited

**Comment by ANRTheBigBoy** [comment]
Grasshopper is strictly better than all the horses.

**Comment by millerj-tc** [comment]
Oh yeah, I was trying to mitigate the fact that the second ability is so play order dependent by giving it a last player upside.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/46321441-ee6b7f00-c5a8-11e8-8cc8-67e7ee32f444.png)

**Comment by ACG8** [comment]
Grasshopper bot is annoying because it prevents simultaneity in the lucid phase. Unless we are still using that rule where you decide the order in which things affect you.

**Comment by millerj-tc** [comment]
Yeah forgot about that. Probably would go with some variation of the dive
version.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/46327001-15d04500-c5c5-11e8-9048-6e3d15010852.png)
