### ISSUE TITLE
Build basic MSE Template

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#30]
Feel free to suggest improvements (or to code improvements yourself - MSE scripts are not executable files, so simultaneous edits are less risky,

**Comment by millerj-tc** [comment]
Looking good so far! That shade of blue for lucid cards might be a bit neon. But I like the slash formatting for the ego/non-ego points.

**Comment by millerj-tc** [comment]
Should there be an icon for when a card has you pay points as a cost, or is it uncommon enough that it should just be in the text box?

**Comment by ACG8** [comment]
We could do that as a different colored circle - one color for resource costs, one color for card costs (burying a card or drawing a card or cuing a card as a cost), and one color for point costs.

**Comment by millerj-tc** [comment]
At the last playtest someone suggested that point tokens and resource tokens be shaped like their respective icons (resources circular and points rectangular). So we could also use the shape of the symbol as an indicator.

**Comment by millerj-tc** [comment]
Could we get a flavor text field  (italics) and the ability to bold keywords (coda/active) and type italicized reminder text?

**Comment by ACG8** [comment]
Yes, I will implement that.
