### ISSUE TITLE
Handless Aggro (Precon project)

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#306]

**Comment by ACG8** [comment]
Can we have both Handless Midrange and Aggro? We won't have enough for them to be built simultaneously.

**Comment by millerj-tc** [comment]
We should create the decklists and then see which is more fun

**Comment by ACG8** [comment]
Dreams
Corrupted By Ruin
The Cleanser
Festival of Time
Danse Macabre

Dives
Dream Expedition
Charge of Israfel
Grant Says No
Down the Rabbit Hole

Lucids
Moment of Understanding
Shelter from the Dark
Robed Counselor
Deluge of Power
