### ISSUE TITLE
Rework Gevurah to bury a prepared card

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#309]

**Comment by millerj-tc** [comment]
It's okay if some oddballs don't bury a prepared card.  Especially if this doesn't wind up in the simple version of the core.

**Comment by ANRTheBigBoy** [comment]
This usually will bury a prepared card when it hits a dive and you pay 5 ya?

**Comment by millerj-tc** [comment]
Yeah, almost always

**Comment by ACG8** [comment]
Good point.
