### ISSUE TITLE
Buff Mountain Tax Collector a little

### ISSUE THREAD

**Issue by ANRTheBigBoy** [ACG8/Lucid#311]
Strictly worse than one of the new top card bury-cost dives.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/46385061-863b9c80-c67f-11e8-8af7-7a6b3b1f04c5.png)

**Comment by ANRTheBigBoy** [comment]
Weak. Make the first one loses w1. Make both buries generic.

**Comment by millerj-tc** [comment]
Are you okay with this? Part of helping midrange should be capping how much disruption hits it.

![image](https://user-images.githubusercontent.com/3642851/46445388-45ee2400-c73c-11e8-8995-484cea04bf39.png)
