### ISSUE TITLE
SFKK

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#316]
![image](https://user-images.githubusercontent.com/3642851/46383406-d31a7580-c675-11e8-8f88-e82b0f0bc7f7.png)

**Comment by ACG8** [comment]
Why not just say "Lose all your will, then gain [w5]"?

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/46384683-23490600-c67d-11e8-8ee7-f4e46de4afe9.png)

**Comment by ANRTheBigBoy** [comment]
Put a minimum cost. I don't like the use-case at 0 will. Like 2 cost and then exhaust in the effect.

**Comment by millerj-tc** [comment]
Cf 0 will case with Aristocratic Mirror
