### ISSUE TITLE
Rules branch based on playtest

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#328]
The testers indicated they would pay between $20 and $45 for the game ($45 was the outlier, Jamie and Deidra both said $20-35 and Carolina said $35). They all said they would play it maybe once or twice a year. (Jamie said he would play it more if the two player experience was solid.)

Overall the playtest went quite well, but we got some really important feedback that mirrored our experience in our test.

First, we want to test an Attack Left restriction.

Advantages:

-  Removes kingmaking and ganging up, super feelbad experiences both for new players and experienced players. We've designed enough interaction on cards that you can still affect the table. In fact, adding this restriction hardly changes the game at all, except for removing these experiences which, while occasionally strategically necessary, are neither interesting nor fun.

-  Simplifies decision making on turns, testers were often arbitrarily waffling on their turn about whose cards to interpret, not based on strategy but on politeness ("Oh, I interpreted Spencer last time, so I'll interpret you this time" -- it's not interesting, it's a time sink, and it makes the game feel more arbitrary)

- We've reworked most dreams (like The Cleanser) to be soft hoses instead of hard hoses, so being forced to interpret a deck that has worse dreams for you isn't that bad and can be considered part of your draft strategy because you primarily pass left

- Makes your turn more predictable and gives you more control so that you only have to plan around one person interpreting your cards.

- Along with this, we would remove positional requirements and shift them into positional incentives, probably along one of these lines:
![image](https://user-images.githubusercontent.com/3642851/46581980-30ac1a80-ca06-11e8-97a1-4cde3a2d28ee.png)
![image](https://user-images.githubusercontent.com/3642851/46581983-36096500-ca06-11e8-9b86-06382e240ff2.png)
(Depending on whether or not we wanted to raise or lower the curve for dives). You'll notice that it also lets us remove words since "interpret another player's prepared card" becomes implicit.

- We think that removing the positional requirements will actually make the game more interesting. You will still have a sense of where someone is likely to go so you can plan around it if you want, but it makes it less of a memory game of having to know exactly which dives someone else has and where it instructs them to interpret. You can just base your strategy on what you think the person to your right wants which is an interesting assessment vs a memory challenge. Jamie specifically noted that the positional requirements on dives made the game feel arbitrary. Like maybe you put something somewhere you don't expect someone to go, but then they do because the dive tells them so. You get hosed and they get rewarded, but not because they were clever, but just because the card told them to do it and maybe you forgot that you shouldn't put something there. That's not an interesting strategic experience.

Second, we want to experiment with "Manual" Lucid triggering. When you have a Lucid in your Lucid zone, during the Lucid phase, you may opt to bury it and trigger the burst ability.

- Testers executed lucid bursts correctly most of  the time, but there was clearly a lot of conceptual confusion about when they could use the burst ability. They had to verbally remind each other/discuss it many times during their first game. It seemed like a pretty clear cognitive block to their planning.

- The functionality of lucids would remain largely the same, but they would become a lot less swingy. Once the lucid is in the zone, you can always choose to burst it. This also brings their functionality more in line with other cards (one interpret = one effect, this time just on a delay and with the opportunity cost of the passive effect)

- The lucid phase becomes more intuitive: use a lucid burst effect if you have one, replace with a new effect

- You gain the interesting strategic choice of whether or not bursting without a replacement lucid is worth it if you lose the passive bonus.

- We lose the consideration of whether or not to jam multiple lucids to achieve your burst effect, but this is a pretty high level strategy and doesn't play into the new player experience at all. Since how lucids work is a core gameplay experience, I think we can and should lower the barrier to entry on them. We can still make complex interesting lucids, but I don't think their base functionality needs to be so swingy and modal.

Third, we want to add some lower costs to the basics. Maybe something like this:

![image](https://user-images.githubusercontent.com/3642851/46582420-f6457c00-ca0b-11e8-93e2-afdec95144de.png)
![image](https://user-images.githubusercontent.com/3642851/46582224-2b9c9a80-ca09-11e8-978a-ba3d39a5eb50.png)

Testers have consistently complained about not having good will sinks in the basics. They also often question the value of drawing cards. These cards give them something easy to do with their secondary resources that show them the value. (They're just ideas, we could do something else.) New players might intellectually understand the benefit of drawing more cards, but if they don't feel like they understand the strategy, the increased options don't necessarily feel meaningful to them. The new Onion Tribe would create a simple dynamic: "If you don't specifically want to draw cards, just choose one of the three that seems cool, bury the other two, and profit." This also feels those particular cards feel less hoser-y to hit in someone else's mind since they are now a lot less narrow. They've long been on the list of "almost trap" dreams.

**Comment by ANRTheBigBoy** [comment]
I was thinking about attack left, and the positional dives only get hosed if you are the last player (so on that single turn that you are going last you can either take your 2/3 risk or hold off for 1 turn).  I bring this up because in the ANR player test they specifically said the opposite. That since spot bonuses are fairly small after the first turn, where to put your cards felt arbitrary, but anticipating the positional dives made it feel way more strategic (ESPECIALLY in the core game, where players are not focused on specific positions from deck-construction). I think we should experiment with attack left, but keeping the positional dives . This also lets us test this change without having to re-design/re-print the card. If it feels bad we can always try removing the positional aspect the next week.

The lucid burst change seems fine. Some cards will need re-balancing (Her true colors for example), but otherwise it's worth trying. We could just remove the lucids as they prove too strong and then add them back as we re-balance them. 

Finally, something we have never experimented with (aside from with 2 players) is alternative draft formats. It's possible we should be testing a draft format with less hidden information. You could watch what the players on your left and right are doing and prepare accordingly. 

Summary:
Try Attack left
Keep positional Dives
Chance lucid burst rule
Experiment with alternative ways of drafting?
