### ISSUE TITLE
Make more Will costs at 4-6

### ISSUE THREAD

**Issue by ANRTheBigBoy** [ACG8/Lucid#329]

**Comment by ANRTheBigBoy** [comment]
Here's some I made.

![image](https://user-images.githubusercontent.com/41978055/46587029-40e6e880-ca4c-11e8-8ea5-7be79d3a724d.png)

**Comment by millerj-tc** [comment]
Hopefully this falls into the subtle category, still CAN work in a control deck, but it becomes pretty useless if you're trying to spend will on a dive and/or lucid burst effect in addition to dreaming.

![image](https://user-images.githubusercontent.com/3642851/46640982-ac0bea00-cb34-11e8-8723-19a6310f3fbc.png)

**Comment by ANRTheBigBoy** [comment]
This is good.
