### ISSUE TITLE
Spirit of Restraint

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#332]
Change second ability to exhaust all will? Lots of text...

**Comment by ACG8** [comment]
![spirit of restraint](https://user-images.githubusercontent.com/10094820/47690941-2b359080-dbbe-11e8-8d13-851609c1ae69.jpg)

**Comment by ACG8** [comment]
It isn't that much text

**Comment by ACG8** [comment]
Of course, now it is much stronger for the player that used it, since they can use up a bunch of will beforehand. Maybe nerf the insight gain?

**Comment by ACG8** [comment]
Or maybe you meant both the original ability plus exhaust all your will. In context, that makes more sense.

**Comment by ANRTheBigBoy** [comment]
Ya, it's supposed to keep the old condition AND exhaust all will.
