### ISSUE TITLE
Secrets of the Sea rework

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#336]

**Comment by millerj-tc** [comment]
Second ability costs 4

**Comment by ANRTheBigBoy** [comment]
I like the original idea. These alternatives vary in power a lot with player count.

**Comment by ACG8** [comment]
Why not "each other player with at least 3 loses 1"?

Also I don't like the second option; too much stuff. First option, but will loss only affects players above threshold

**Comment by ACG8** [comment]
![2dfe47bc-6ec3-46a1-911c-db5cc46ce87a](https://user-images.githubusercontent.com/10094820/51009641-879a2200-1516-11e9-80aa-770775083dd2.jpg)

**Comment by ACG8** [comment]
![2dfe47bc-6ec3-46a1-911c-db5cc46ce87a](https://user-images.githubusercontent.com/10094820/51010286-37708f00-1519-11e9-95d9-553d7f7bd51f.jpg)
