### ISSUE TITLE
Rework Reckless Duo

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#337]
Second ability mandatory?

**Comment by millerj-tc** [comment]
Second ability sacrifice 4

**Comment by millerj-tc** [comment]
I like this solution better:

![image](https://user-images.githubusercontent.com/3642851/47964580-9be70d80-e001-11e8-83a5-639f64954e78.png)

**Comment by ANRTheBigBoy** [comment]
This looks so much more awkward than an "if you do" clause.

**Comment by ACG8** [comment]
Why not make the second ability a normal will cost rather than a sacrifice? Also, I would put the "Lose 2" on its own line after the interpret.

**Comment by ACG8** [comment]
![76cce08b-10da-4fca-8931-2c6bd0ed1dac](https://user-images.githubusercontent.com/10094820/51008922-87e4ee00-1513-11e9-8957-1a52d7a67b91.jpg)

**Comment by ACG8** [comment]
![76cce08b-10da-4fca-8931-2c6bd0ed1dac](https://user-images.githubusercontent.com/10094820/51010235-055f2d00-1519-11e9-9f95-a53bde8df685.jpg)
