### ISSUE TITLE
Try hard mode

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#338]
Make second ability lose 1 will and remove exhaust effect

**Comment by ACG8** [comment]
![marine_tutorial_by_neisbeis_d2vqb3q-pre](https://user-images.githubusercontent.com/10094820/51008223-84039c80-1510-11e9-9501-c982a85ff62e.jpg)

**Comment by ACG8** [comment]
![marine_tutorial_by_neisbeis_d2vqb3q-pre](https://user-images.githubusercontent.com/10094820/51008233-94b41280-1510-11e9-8ca1-c98b95a116cf.jpg)

**Comment by ACG8** [comment]
![0e89484a-aa0f-454f-9b0f-29cdffc61948](https://user-images.githubusercontent.com/10094820/51008643-3e47d380-1512-11e9-8dbd-cdd3532a104e.jpg)
