### ISSUE TITLE
Blood Engine Mech

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#339]
Can we change it to something like this? I hate the current wording:

![image](https://user-images.githubusercontent.com/3642851/47958122-e1202680-df92-11e8-94e5-8f4228be1e67.png)

**Comment by ACG8** [comment]
Approval

**Comment by ACG8** [comment]
![d8sdmwi-34c04946-cb0e-4342-a082-5420b68856fa](https://user-images.githubusercontent.com/10094820/51008754-b57d6780-1512-11e9-9d51-5c2e76159ba0.jpg)
