### ISSUE TITLE
Begin Game with Lucid

### ISSUE THREAD

**Issue by ANRTheBigBoy** [ACG8/Lucid#340]
Each player starts the game with a random one of their lucids already active. This will help smooth out the early game and remove those few feel-bad games where you can't get a lucid active for ages. 

This also makes the dive-phase lucids kinda cooler, along with the lucids where the burst ability has no cost (when have gotten a little lackluster now that their flexibility doesn't matter as much since the lucid rules change). This makes turn 1 hands more interesting, since it's not obvious if you want 1 of each card-type anymore. 

As a bonus, we can get rid of external randomization for first player. The player with the lucid with the alphabetically first title goes first (or something like that).

**Comment by ANRTheBigBoy** [comment]
We could call this lucid your "inspiration". :P

**Comment by ACG8** [comment]
I am in favor of all aspects of this proposal
