### ISSUE TITLE
Solveig Classy Angel

### ISSUE THREAD

**Issue by ANRTheBigBoy** [ACG8/Lucid#341]
First ability should not be a bury cost, as per our discussion about targeted hosing today. I think it's incidental enough that it can just be removed.

**Comment by ACG8** [comment]
![ms__elf_by_dopaprime_dcfkj1d-pre](https://user-images.githubusercontent.com/10094820/51008000-74d01f00-150f-11e9-81c1-2176bf5ed2b9.jpg)

**Comment by ACG8** [comment]
![ms__elf_by_dopaprime_dcfkj1d-pre](https://user-images.githubusercontent.com/10094820/51008743-a26a9780-1512-11e9-83d2-e35926f46030.jpg)
