### ISSUE TITLE
Cards that are Bad/Cards that I miss

### ISSUE THREAD

**Issue by ANRTheBigBoy** [ACG8/Lucid#342]
Here are some cards that are bad which I think should be cut from the current pool:

Forest Witch's Command
Frost Witch's Proclamation
Ivory Witch's Directive
Scary Face Knife Knife

I think to replace them, we should add back in some prepare effects. This serves as an indirect buff to handsize, since it's another way to take advantage of having lots of cards. 

Horsepower
Nightmare
Identity Shift
Canny Astrowizard

**Comment by ACG8** [comment]
Agree with more prepare effects.

**Comment by ACG8** [comment]
![6e873032-2f34-4bcd-bb75-2e1b73ad4904](https://user-images.githubusercontent.com/10094820/51010737-380a2500-151b-11e9-903b-8f281eb18d5c.jpg)

**Comment by ACG8** [comment]
![79d5ac22-cfab-4eef-874b-210f6066bcc0](https://user-images.githubusercontent.com/10094820/51010878-d1393b80-151b-11e9-8e4a-0c57c87f5add.jpg)

**Comment by ACG8** [comment]
![96df6526-9977-4a0a-b109-67451053a3cb](https://user-images.githubusercontent.com/10094820/51010904-eada8300-151b-11e9-9ecc-f01fd3ea7688.jpg)

**Comment by ACG8** [comment]
![7db6e8be-973f-47fa-a06e-f998ed85e691](https://user-images.githubusercontent.com/10094820/51010986-3e4cd100-151c-11e9-978e-8181dd71295d.jpg)

**Comment by ACG8** [comment]
![abstract_black_horse_by_astoko_dc82fgo-fullview](https://user-images.githubusercontent.com/10094820/51011141-eebad500-151c-11e9-8a26-c80cf6a3daf1.jpg)
