### ISSUE TITLE
Non mandatory costs (danse macabre)

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#345]
Make the will lost second so that it feels less like an if-then construction, ie "Gain i4 and lose w2" or whatever it is

**Comment by ACG8** [comment]
![corrupted by ruin](https://user-images.githubusercontent.com/10094820/51007111-e5753c80-150b-11e9-84ca-31eb8c1edac5.jpg)

**Comment by ACG8** [comment]
![no-name](https://user-images.githubusercontent.com/10094820/51007246-5ddbfd80-150c-11e9-9882-6bd2b3cb5eb8.jpg)
