### ISSUE TITLE
Festival

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#347]
Gain 6, other gain 3

**Comment by ACG8** [comment]
![no-name](https://user-images.githubusercontent.com/10094820/51446978-b36b9380-1cde-11e9-94e3-352e8edefaa3.jpg)

**Comment by ACG8** [comment]
![no-name](https://user-images.githubusercontent.com/10094820/51448302-44486c00-1ceb-11e9-91bb-e3d09d4b5d42.jpg)
