### ISSUE TITLE
Create a Stone Arch Games logo for box

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#360]

**Comment by ACG8** [comment]
deepdreamgenerator + game-icons.net can make some pretty cool icon designs:

![196cd28a6d392c5b718a27a6f661516b4942a5f7](https://user-images.githubusercontent.com/10094820/52246411-5c071f00-28ab-11e9-8471-03331364543b.jpg)

**Comment by ACG8** [comment]
![01457387a4ada159eea57df8650e57af48f6f272](https://user-images.githubusercontent.com/10094820/52251788-8dd8af80-28c4-11e9-9f7f-37e5326da5e7.jpg)

**Comment by ACG8** [comment]
![6f5e56058867b30b0d4941f68e6a3b57b50c6bfa](https://user-images.githubusercontent.com/10094820/52316540-6c89c900-2981-11e9-86e2-939492610582.jpg)

**Comment by ACG8** [comment]
![d8e8a99086d3fafa1ac700a98a6ccfab7cb356c8](https://user-images.githubusercontent.com/10094820/52318419-0786a100-298a-11e9-80bb-4b4ff6798ee8.jpg)

**Comment by ACG8** [comment]
![6f5e56058867b30b0d4941f68e6a3b57b50c6bfa](https://user-images.githubusercontent.com/10094820/52379170-4f133880-2a2f-11e9-9002-03a258d81540.jpg)

**Comment by ACG8** [comment]
![d03884c8eb5df9e93cf1bf511fe76e6a05c7e343 1](https://user-images.githubusercontent.com/10094820/52379180-5a666400-2a2f-11e9-96d9-0aed90ec8f83.jpg)

**Comment by ACG8** [comment]
![5856c35b33029a3ac4f458efc19aa9fd25e2600b](https://user-images.githubusercontent.com/10094820/52380320-efb72780-2a32-11e9-961b-78b1a54a4aa1.jpg)

**Comment by ACG8** [comment]
![d60ff05f7ccd27051fad7f24a33d21bd32068b1a](https://user-images.githubusercontent.com/10094820/52381502-5a6a6200-2a37-11e9-8faa-10e778d050b2.jpg)

**Comment by ACG8** [comment]
![5ffb406c1db131045d35bcc21787ae06fb4044d8](https://user-images.githubusercontent.com/10094820/52384840-c1424800-2a44-11e9-978f-825c6227ec48.jpg)

**Comment by ACG8** [comment]
![d69b637e02b0da99363dc874cfe8fc5e91df7463](https://user-images.githubusercontent.com/10094820/52387657-ba213700-2a50-11e9-8d45-d96232e08b50.jpg)

**Comment by millerj-tc** [comment]
I like the one I marked except I think less blur would be good

**Comment by ACG8** [comment]
You prefer the small font to the larger font?

I can try focusing on different stone-like textures in general

**Comment by millerj-tc** [comment]
Could you send me the original files. Do we own both of them/are they
creative commons?

**Comment by ACG8** [comment]
![stone-bridge 3](https://user-images.githubusercontent.com/10094820/52452670-a1c12300-2b09-11e9-9222-3c22d6be868f.png)
![stone-bridge 2](https://user-images.githubusercontent.com/10094820/52452672-a1c12300-2b09-11e9-8841-e33f64bff79e.png)

These are from game-icons.net. The license is here:
https://creativecommons.org/licenses/by/3.0/

**Comment by ACG8** [comment]
The pattern is one of the default patterns on deepdreamgenerator ("Stones")

**Comment by millerj-tc** [comment]
I like this better because there are less blurry elements and the letters are sharper. The way I did it was I separated the letters and icon into two separate images and ran them through DDG individually. That way the sharpness of the letters is maintained and then you can just paste them on as a layer over the image. I think it would work better with the smaller text, but you get the idea. I ran out of dreams, so I can do more later or you can iterate on it more.

![image](https://user-images.githubusercontent.com/3642851/52454150-29119500-2b10-11e9-91f1-2db350b78fe6.png)
