### ISSUE TITLE
How many functional reprints can the game sustain?

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#37]

**Comment by ACG8** [comment]
Had to look up the definition of functional reprint. One question is what qualifies. If a card is identical to another card but on a different emotional axis, is it a functional reprint? I'm not sure if there is a necessary limit, other than wanting to avoid having too many identical cards in a deck.

**Comment by millerj-tc** [comment]
Yeah, like the question is basically: if you can play 4 different channels
that are just slight variations of "gain 2 will," is that a reductive
strategy (one that is super strong but makes deckbuilding uninteresting).

But yeah emotional axes solve pretty well because it could only be a
problem if there were too many "neutral" effects like that or too many that
were on both sides of an axis.

I still think it's worth knowing though because it might limit where we can
put cards on the axes.

On Jan 20, 2018 05:40, "Ananda" <notifications@github.com> wrote:

Had to look up the definition of functional reprint. One question is what
qualifies. If a card is identical to another card but on a different
emotional axis, is it a functional reprint? I'm not sure if there is a
necessary limit, other than wanting to avoid having too many identical
cards in a deck.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ACG8/Lucid/issues/37#issuecomment-359165284>, or mute
the thread
