### ISSUE TITLE
New Lucids

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#381]
![image](https://user-images.githubusercontent.com/3642851/55929862-5a781100-5be4-11e9-8b2e-ef19356746f7.png)
![image](https://user-images.githubusercontent.com/3642851/55929863-5c41d480-5be4-11e9-9b01-2fa2a88c6fb4.png)
![image](https://user-images.githubusercontent.com/3642851/55929865-5d730180-5be4-11e9-86c3-6312adf49dd2.png)
![image](https://user-images.githubusercontent.com/3642851/55929867-5ea42e80-5be4-11e9-8555-4d3ad6e3f8b1.png)
![image](https://user-images.githubusercontent.com/3642851/55929870-5fd55b80-5be4-11e9-9f5e-d3a86f9bd34c.png)
![image](https://user-images.githubusercontent.com/3642851/55929874-61068880-5be4-11e9-9395-9e2e51a23b45.png)
![image](https://user-images.githubusercontent.com/3642851/55929875-6237b580-5be4-11e9-849b-8094116581f8.png)
![image](https://user-images.githubusercontent.com/3642851/55929878-6368e280-5be4-11e9-8fc5-36b71ee91f98.png)
![image](https://user-images.githubusercontent.com/3642851/55930172-ca3acb80-5be5-11e9-975c-f248b8c8721f.png)
![image](https://user-images.githubusercontent.com/3642851/55930131-91025b80-5be5-11e9-9a82-ac9937b4b021.png)

**Comment by ACG8** [comment]
I think we should probably make a different issue for each of these. Too hard to track them all in one issue.

**Comment by ACG8** [comment]
Moved each card to its own issue so we can more easily discuss them individually.
