### ISSUE TITLE
Pillar of Fire

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#382]
![](https://user-images.githubusercontent.com/3642851/55929862-5a781100-5be4-11e9-8b2e-ef19356746f7.png)

**Comment by ACG8** [comment]
This is a great Lucid for willful hand-less decks. The art is great too.

**Comment by ACG8** [comment]
Plus it is a very strong card to start with.

**Comment by ANRTheBigBoy** [comment]
Gain w3 is too strong. It needs a cost, or some kind of drawback (maybe giving other players will too?)

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/56011370-eeadab00-5cac-11e9-80e6-b57300834e51.png)

**Comment by ANRTheBigBoy** [comment]
I think they should draw 2. Gain w3 for nothing is huge.

**Comment by ACG8** [comment]
Still need clarification from @ANRTheBigBoy about whether any further changes to Pillar of Fire are needed.
![no-name](https://user-images.githubusercontent.com/10094820/57576838-56cbea00-742f-11e9-903a-1b964727857f.jpg)

**Comment by ACG8** [comment]
![no-name](https://user-images.githubusercontent.com/10094820/57577117-ab726380-7435-11e9-8b8a-6276fe4df91f.jpg)
