### ISSUE TITLE
Sunset of the City

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#385]
![](https://user-images.githubusercontent.com/3642851/55929867-5ea42e80-5be4-11e9-8555-4d3ad6e3f8b1.png)

**Comment by ACG8** [comment]
The passive ability seems very fiddly for little gain. It is also weak enough that I don't think the "If you didn't interpret your own dive" is necessary.

**Comment by ANRTheBigBoy** [comment]
Simplify this first ability. Maybe just have it draw 2 cards?

**Comment by millerj-tc** [comment]
It's supposed to be in the handless deck

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/56011185-12242600-5cac-11e9-99d8-4b364832c202.png)

**Comment by ANRTheBigBoy** [comment]
OK
