### ISSUE TITLE
Ascent by Escape

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#386]
![](https://user-images.githubusercontent.com/3642851/55929870-5fd55b80-5be4-11e9-9f5e-d3a86f9bd34c.png)

**Comment by ACG8** [comment]
Absolutely love this one. I think we found in the past that "prepare top card" is much weaker than "prepare a card", so should be fine.

**Comment by ANRTheBigBoy** [comment]
These two abilities are an anti-combo. The 2nd is good when you don't have a prepared lucid, and the first ability gives you random prepared cards (which could be lucids). The fall-back of draw 1 card is too weak. 

Both these abilities are cool, but should not be on the same card.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/56011341-cde55580-5cac-11e9-8582-a87ccb687e53.png)

**Comment by ANRTheBigBoy** [comment]
Very text-heavy. It's cool though.
