### ISSUE TITLE
Curious Bauble

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#387]
![](https://user-images.githubusercontent.com/3642851/55929874-61068880-5be4-11e9-9395-9e2e51a23b45.png)

**Comment by ACG8** [comment]
Love the art/name on this one. Passive ability seems rather strong.

**Comment by ANRTheBigBoy** [comment]
Wow this is slow. It could work though. If you start the game with this and don't get to w3 on turn 1 though, you get totally wrecked. Bit of a turn-1 variance card...

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/56011543-ba86ba00-5cad-11e9-82ee-b924a01b6288.png)

**Comment by ANRTheBigBoy** [comment]
Nice
