### ISSUE TITLE
Taika the Glorious

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#389]
![](https://user-images.githubusercontent.com/3642851/55929878-6368e280-5be4-11e9-8fc5-36b71ee91f98.png)

**Comment by ACG8** [comment]
Not sure how I feel about the cost on the second ability; it is already a difficult condition to meet and 8 points means you are forgoing playing your cards. Maybe try it with no cost first and see if that is too powerful? It is already fairly complex, so reducing the complexity would be another benefit of removing the cost.

**Comment by ACG8** [comment]
Or maybe if you buried your hand after doing it?

**Comment by ANRTheBigBoy** [comment]
This passive is the same as Hidden Walkway. 

This is a bit heavy on the text... The 2nd ability is a bit of a hair-puller.

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/56007222-9e7b1c80-5c9d-11e9-8f63-3b2ae1cf29db.png)

**Comment by ANRTheBigBoy** [comment]
Looks much better.
