### ISSUE TITLE
Hidden Walkway

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#390]
![](https://user-images.githubusercontent.com/3642851/55930172-ca3acb80-5be5-11e9-975c-f248b8c8721f.png)

**Comment by ACG8** [comment]
Seems good. I like the effect (interpreting dreams from hand is not something we have right now), but the art could probably be replaced.

**Comment by ANRTheBigBoy** [comment]
Great. Since the will-cost is going to be tacked-on to w/e you need to spend on the dream, I think 4 is a bit high. 3 seems right to me.

**Comment by ACG8** [comment]
![no-name](https://user-images.githubusercontent.com/10094820/57576662-02bf0680-742b-11e9-9a88-ed3c8a9754ff.jpg)
