### ISSUE TITLE
Rules Clarifications from 1/21 Playtest

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#42]
"Stopgap solution" means however we ruled in the moment to keep the playtest going.
Long-term Solution is my proposal for how we should officially rule going forward, feel free to propose alternatives

Question: Do you declare the dive location as part of the dive declaration? In other words, do "after a  dive is declared" effects happen before or after dive location  is stated?
Stopgap Solution: Yes, happens as part of declaration
Long-term Solution: I think they should work as in stopgap

Question: Does a player whose mind is guarded also have their hand guarded?
Stopgap Solution: Yes
Long-term Solution: I think "yes," because that way the game state is simpler -- a player is guarded, not either their hand or mind

**Comment by ACG8** [comment]
I agree on both counts
