### ISSUE TITLE
0.07 Demon Guide Duel Deck replacement

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#46]
Demon Guide is a little unintuitive: it gives 0 base ego points, has a first ability that can feel like a downside, and a third ability that is relatively complex.

Often you only use the first Demon Guide ability once, you pay the 4 insight, and then gain enough to use the second ability. This means you're really only paying 1 insight for: 2 anima, 2 will, and an access. And the only downside is that you can't do it immediately.

What if Demon Guide looked like this instead:
Demon Guide
0/2 Channel
The diver may either:
- Gain [a2] if they have [a2] or less
- [a4]: Coda - Access another player's bottom card and gain [i3].

This way the first ability is roughly the same: something you only do once, but is very efficient at gaining anima. And it shifts the tempo disadvantage: rather than setting you back insight, it prevents you from doing both abilities in the same turn.

**Comment by ACG8** [comment]
I like it. Though +[a2] if they have [a2] or less might be a little awkward since it sort of punishes you if you access it with [a1] rather than [a2]; that is just a minor detail though.
