### ISSUE TITLE
Make Elites starter deck

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#5]
Faction focuses on protecting high value secrets that score points at end of game or have other utility powers. Also mind cards that score points if not banished.

**Comment by millerj-tc** [comment]
@ACG8 I had to add an extra rule in the rulebook to confirm the common sense way of handling face up cards on top of minds because of Stalwart Guardian, but I think that design is really cool. What do you think? I think eventually we should explore that space, but maybe it's not starter set?

**Comment by ACG8** [comment]
Sounds good to me. I don't think it is too much for the starter set.

When you update the rulebook, would you mind also updating the copy of the rulebook in the wiki?

**Comment by millerj-tc** [comment]
The rulebook in the wiki is the only one I'm maintaining now, so it's already up to date.

**Comment by ACG8** [comment]
You're right, I just didn't see that line. Thanks.
