### ISSUE TITLE
0.07 New Faction Guidelines

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#50]
Most Consistent Point Gains ---- Most Scaling Point Gains
Libertines -- Mercenaries -- Elites -- Thieves -- Therapists

Mercenaries
- draw cards theme (after another player declares dive you, rearrange top cards)
- ‎hand interaction theme?
- ‎channel: each player draws their top card or loses 2 insight
- ‎Draw cards from bottom, etc
-‎ ego access traps
-‎ channel (2/2): The ego gains 1 insight and each other player may pay (2w) to gain 2 insight
- ‎ID: After the prep phase you may pay 3 will to guard another players mind and gain 3 insight.

Elites
- Lucid: After dive declared on your mind, Reveal cards from mind then shuffle/reorder them and return them to your mind.
- Lucid (0/1): [w1]: After a dive is declared on you, you may draw your top card and gain 1 insight. Cue this card
-‎ Will ramp

**Comment by millerj-tc** [comment]
A Symphony of Shattered Doors could be an Elite card -- works well early when you go trap - channel, and then good late for disrupting people.

**Comment by millerj-tc** [comment]
Simplified Alien Gameshow could go in either deck (probably Elites?):
0/2 Lucid
After a dive is declared on your hand, the diver may gain [i2] and cancel the dive. If they do, you gain [w1] for each card in your hand.

**Comment by ACG8** [comment]
I don't think that version of Alien Game Show provides enough incentive for the diver to cancel the dive; [i2] is what you would get for accessing a lucid, and that is pretty disappointing already. The trigger is also a little awkward since it says the diver may do something but you are the one playing the card. I suggest the following.

After a dive is declared on your hand, you may offer the diver [i3] to cancel the dive. Gain [w1] if they accept.

[a2]: If they refuse, seek one trap from your mind, then shuffle.

Offer and seek are new, useful keywords. Offer means provide a choice to another player; the resources offered come from the general supply, not from the player making the offer. Seek (for either of these, I am open to other names) means to search your mind for a card matching the specification, reveal it to all players, then draw it.

It also occurs to me that we could simply use "Shuffle" to mean "Shuffle your mind" (what else would you shuffle?) In cases where you are directed to shuffle another player's mind, it could specify the player.

**Comment by millerj-tc** [comment]
I don't think we need a new keyword for providing a choice since the word "may" already does that. Channels already offer the diver a choice, so I don't think putting that on a lucid is any more awkward. It will never be ambiguous who the diver is since the trigger is a dive being declared on your hand. I don't think we should add keywords that can easily be replicated through regular rules of grammar. Like, if a card says "You may do either A or B" we don't need a keyword that says "FORK DECISION: A or B" because the plain way of saying that already accomplishes exactly what we want and cuts down on specialized terminology. If anything we could change the wording to "the diver may choose to" to make it clear that it's up to them.

I also think [i2] is fine as a payoff. Imagine my hand is trap/Gameshow. Someone dives my hand. I play the Gameshow. Now we can either both profit if they take the Gameshow, or I can profit if they try for the trap. So it's in their interest to take the Gameshow if they think I have a trap. But if my hand is Gameshow/channel, then it's in their interest to skip the Gameshow. So basically it comes down to what they think the other card(s) in my hand are. I think that's a fine dynamic to create -- it's kind of like a Forest Guardian Sniper interaction.

Your proposed rules text is >140 characters.

The "seek" mechanic (commonly referred to as a "tutor" mechanic because of [this card](https://magiccards.info/me4/en/77.html)) is an interesting one. It tends to be super powerful in many games unless it's tightly constrained. I don't necessarily mind experimenting with it -- even as a duel deck effect -- but I don't think this is the right place for it. The card we're talking about is already a bit weird. I think if we want to test out "seek," we put it on a simpler card.

Remember we're making duel deck cards (or at least that's what I was talking about in all these comments). They should be the _simplest possible version of the card_ that fits in with the faction theme. We should try to avoid tacking a bunch of new experimental things together.

Maybe an Elite card could be:
Stalwart Guardian Returns
0/3 Lucid
[w1]: After a dive is declared on your hand, seek a trap from your mind, then shuffle.

**Comment by ACG8** [comment]
> I also think [i2] is fine as a payoff. Imagine my hand is trap/Gameshow. Someone dives my hand. I play the Gameshow. Now we can either both profit if they take the Gameshow, or I can profit if they try for the trap. So it's in their interest to take the Gameshow if they think I have a trap. But if my hand is Gameshow/channel, then it's in their interest to skip the Gameshow. So basically it comes down to what they think the other card(s) in my hand are. I think that's a fine dynamic to create -- it's kind of like a Forest Guardian Sniper interaction.

Yes, but they wouldn't dive your hand in the first place if they thought it was a trap. They also probably wouldn't dive your hand if they thought they were going to get a 0/2 lucid, which is effectively what this choice is (except without depriving the ego of a valuable resource).

How about this:

After a dive is declared on your hand, the diver may gain [i3] and cancel the dive. If they do, you gain [w1].
