### ISSUE TITLE
New Thief Passive

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#51]
Do you like this new thief passive and if so what do you think it should cost?

"As your dive, reveal two random cards from another player's hand and access one of them."

I think it feels thief-y and helps reduce Mind Rabbit variance which makes that a more viable alternative strategy rather than just something you occasionally do because you can.

**Comment by ACG8** [comment]
Not sure reducing Mind Rabbit variance is necessary; I see the MC of Despair as a form of Trap Insurance. But it seems fine. Not sure if 2 is too expensive; more choices is helpful, but not necessary that helpful depending on what they have in their hand. On the other hand, 1 feels pretty cheap.
