### ISSUE TITLE
"As your dive"

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#52]
What if we switched over the access-based lucids to be "as your dive" cards?

For instance

Mind Thievery
0/2 Lucid
As your dive, access another player's top card. If that card, is a channel, gain [i2].

Mind Rabbit
0/2 Lucid
1/2: As your dive, access a random card in another player's hand and gain [i2].

I think this keeps the design space more open because a big thing we have to watch out for is chaining combos. Since you typically only get one dive per turn, this means that you have to use these kinds of lucids very intentionally rather than just playing them because they're in your hand when you happen to hit a channel or whatever. (Mind Rabbit is still a hedge, but people who use Mind Rabbit at the correct time will be rewarded over those who run a 3 trap hand just to trigger the Rabbit.)

For example, the new thief passive (which isn't in the game, but something like that almost certainly will be at some point) enables a very strong Mind Rabbit/Forest Guardian Sniper combo. And that's just one example, I think a lot of stuff like that is likely to crop up since these types of lucids are "free" right now -- they're almost like extra turns! Even if they cost will, they allow really big (sometimes random) swings.

Let me know what you think.

**Comment by ACG8** [comment]
Yes, I like this. Prevents stacking dive buffs, and allows for powerful effects that derive their power from NOT being 'As your dive'.
