### ISSUE TITLE
New Elite cards

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#58]
A new channel that gains will in an Elite-y way, and a new Lucid that is more straightforward than Hourglass. The new card should have a will or insight gain effect.

**Comment by millerj-tc** [comment]
I'm a little worried that Trusted Confidante requires too much work and that Cosmic Paranoia is still too complicated for someone playing their second game.

Could we change Cosmic Paranoia to read: "Instead of your dive, bury your hand..."

Otherwise I think it makes it ambiguous whether you also get to dive after doing the card effect.

I think it's worth trying them out though.

**Comment by millerj-tc** [comment]
I also think maybe we need to reduce the card draw on CP.

Imagine I have three cards in hand and put D Door on top. I play my D Door and bury it and draw three cards (Five cards in hand, D Door is the 5th card in my deck). I play CP to draw into D Door (my entire deck is in my hand). At the end of the turn, I bury down to three cards, putting CP on top. Now I put D Door on top, bury it, draw three cards (one of which is CP) and repeat the loop. I can use my best channel every other turn. PLUS since CP let's me tap will to gain i3 every turn when I'm NOT D Dooring.

This seems too good, right?

**Comment by ACG8** [comment]
Also, you can't have your entire deck in your hand (in the example scenario) because Cosmic Paranoia forces you to bury your hand before drawing.
