### ISSUE TITLE
MSE Format for Recurring Mana Costs

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#66]
@millerj-tc I am running into some trouble with the formatting change, because the icons are so small that any recycle symbols I can put on the icon are too small and overshadowed by the number. Let me know if you have any ideas. I think the simplest solution would to make recurring costs have the same shape but a different color; I just don't know what the color should be.

**Comment by millerj-tc** [comment]
Can you make the icon slightly bigger so that the arrows straddle the edge of the circle?
Maybe make spend cost circle slightly reddish and then the tap cost circle green? Implying burning through resources vs a more sustainable approach?
