### ISSUE TITLE
0.08 All cards are played from hand

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#70]

**Comment by millerj-tc** [comment]
@ACG8: If all cards are now played from hand, what is the difference between channels and dives? At the very least it seems like Tunnel of Wealth should be a channel and Room of Mirrors should be a dive. (That way "dive" cards always mean cards that let you access/mess with opponent cards. If this is the definition we go with, then the elite dives will need to change.)

**Comment by ACG8** [comment]
The difference between channels and dives is that when an opponent accesses a channel they get to use its ability; when they access a dive, they don't.

**Comment by millerj-tc** [comment]
I guess my reasoning is that I like dives always being interactive because it means that a third of your deck is always interactive. So you can't build the "non-interactive" deck where you play all the dives and channels that don't interact at all. But I dunno, I'm not dead set on it I guess. Do you have a particular reason for wanting to design non-interactive dive cards?

**Comment by ACG8** [comment]
No, I don't. I think the Mirror should be a channel, but if you feel strongly that Tunnel of Wealth should be a channel we can do that; I mostly wanted it to feel different from Fungal Discovery and Fallen Titan, which are pretty similar.

**Comment by millerj-tc** [comment]
Let's leave it for now and see if testers ask the types to be more distinct
