### ISSUE TITLE
0.08 Neutral Cards

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#72]
I just uploaded these; I'll make issue for the other factions. It turns out you can open old files with the new template, with only minor changes needed.

**Comment by millerj-tc** [comment]
Can you upload PDFs so I can view on mobile?

**Comment by millerj-tc** [comment]
Do we need to specify "the diver" anymore? There should be a general case right -- the person who access the card, and then an exception to the general case ("the ego does x").

That way, Fungal Discovery reads: "Gain [w1] and [i2]"  and Trusted Confidante reads: "The ego reveals and buries their hand. You gain [w1] per buried Lucid." or something similar.

(I think cards that reference the "ego" can just say "you" when talking about the diver.)

**Comment by ACG8** [comment]
I would be up for removing the diver entirely; that makes sense. I'll edit the cards made so far to adhere to that. I'm not sure we even need to include "you".

**Comment by ACG8** [comment]
I would be up for removing the diver entirely; that makes sense. I'll edit the cards made so far to adhere to that. I'm not sure we even need to include "you".

**Comment by millerj-tc** [comment]
On Dream Factory: What does "declaring a dive" mean now?

**Comment by ACG8** [comment]
Accessing a card from your hand or playing a dive card (and resolving any targeting for that card)
