### ISSUE TITLE
0.08 Therapist Deck

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#74]

**Comment by ACG8** [comment]
Going to start working on this now

**Comment by millerj-tc** [comment]
I was thinking their theme could be "bring subconscious to conscious" -- they make everyone draw and/or reveal cards for group benefit but more therapist benefit.

**Comment by ACG8** [comment]
Sure. I think I need to change the ID theme though - shadowstalker may not fit anymore, without traps.

**Comment by millerj-tc** [comment]
Yeah that's fine

**Comment by millerj-tc** [comment]
Forest Ark + Facade leads to quarterbacking -- "Don't reveal your hand, he is obviously holding Facade!" I really like Ark, maybe rework Facade?

New Spinning Yarns seems a little OP.

**Comment by ACG8** [comment]
The only difference with the new spinning yarns is that players can draw a card and it is more difficult to get will out of it. I'll change it back, though.
