### ISSUE TITLE
Allow random hand access as base mechanic?

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#79]
It seems weird that every single card has "outsider insight" while it also still feels like there are a limited number of ways to access cards. Like why not just add points to the dive cards instead? Like the subtle variation between 2 and 3 outsider points kind of matters, but it feels a bit sloppy to me.

**Comment by millerj-tc** [comment]
Yeah, I like that idea. Let's say for all the cards we create right now it's a rule, and then if we design a card that only feels balanced by changing that number we can try it.

**Comment by millerj-tc** [comment]
So will random hand access of another player be a base mechanic then?

**Comment by ACG8** [comment]
I don't think it should be. The rules are so much more elegant without it. I think we just need to make hand access dives accessible to everybody.
