### ISSUE TITLE
Allowing multiple dives on the same player per turn?

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#8]
Do we need to make a rule that each player can only be dived once per turn? Otherwise, they might feel ganged up on them if people keep burying/channeling their cards?

**Comment by ACG8** [comment]
Maybe. Though I don't think you want to prevent a player from diving themself if somebody has already dived them. I think it is probably all right though; it encourages players to keep some traps and barriers handy in case people start piling into their mind.
