### ISSUE TITLE
5 themes

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#87]
Decide on 5 themes to focus on for card design

Make sure to include more will payoff cards, especially dives.

Design 2 IDs to go with each theme: one more linear, and one more modular.

**Comment by millerj-tc** [comment]
Google Sheet for organizing themes: https://docs.google.com/spreadsheets/d/1WzcCdW_4e3lLuIskqy096Jm0f_ks6FzTSq1C0ptdRew/edit?usp=sharing

**Comment by millerj-tc** [comment]
What should the 5 themes be? 

I think Minotaureen/non-prepared access is a good one.

"Snipe" could be a theme (Mind Thievery type effects -- cards that give you information and cards that pay you off for using that to make "called shots" on the game state.)

**Comment by millerj-tc** [comment]
DREAM ANALYSIS PROTOCOL
Theme based around a dive that says:

"Access a card at random from your own hand."

**Comment by ACG8** [comment]
Well, based on existing cards:

Handless theme (rewards you for not having a hand of cards)
Anti-handless theme (opposite of handless theme, punishes other handless players)
Rush (Short term gains and ending the game fast by giving out lots of points)
Combo Dive (Powerful but fragile dive chains involving accessing your own prepared cards)
Escort (Easy gains when other players don't target you)

**Comment by millerj-tc** [comment]
I think there is a distinction between an archetype and a theme in drafting. So in Magic, "aggro" (end the game early) is an archetype, whereas a theme is more like a mechanic that can fit into multiple archetypes. For instance, "Landfall" was a theme -- it was a mechanic where cards would give you bonuses when you played a land card. There were aggro Landfall decks and control/lategame Landfall decks. There were some Landfall cards that were good enough value that you could play them by themselves (modular) and some Landfall cards that were only really good if you were playing a bunch of other Landfall cards (linear).

I think we should also be careful about designing themes that are too much of an RPS situation -- where one theme is clearly designed to counter another. That tends to lead to uninteresting drafts.

So it's okay to have handless/anti-handless **cards** because you do want to give people tools to deal with certain kinds of strategies, I just don't think they are necessarily themes.

**Comment by millerj-tc** [comment]
Theme:
Symmetrical Actions (like Merfie the Finder)

**Comment by ACG8** [comment]
1. Theme built around burying your own top card (cycling through your mind faster).
2. Theme built around revealing and burying cards instead of accessing them to gain alternative benefits.
3. Theme built around returning prepared cards to players' hands
4. Theme built around manipulating the order of cards in your mind (for example, ordering them so that all the channels are together)

**Comment by ACG8** [comment]
Sure, that sounds good.
